### ISSUE TITLE
Updating radarr through the dockerfile

### ISSUE THREAD

**Issue by aaomidi** [linuxserver/docker-radarr#1]
Hey :)

It seems that radarr does not update using the dockerfile.

**Comment by sparklyballs** [comment]
i'm not sure what you mean

**Comment by aaomidi** [comment]
When radarr/radarr updates, this dockerfile does not grab the new version from the repo when restarted using `docker restart name`

**Comment by sparklyballs** [comment]
we ditched updating dockers that way middle of last year
we had too many issues with doing things that way

**Comment by aaomidi** [comment]
I see, so I have to recreate the docker every time I want to update it or?

**Comment by sparklyballs** [comment]
yes

stop and remove the docker container, pull new image and start a new container
