### ISSUE TITLE
Mono : Disable debug mode

### ISSUE THREAD

**Issue by But4ler** [linuxserver/docker-radarr#10]
Hello
By default, Mono is in debug mode
Is it possible to delete this? For a common use, it is not really useful
[https://github.com/linuxserver/docker-radarr/blob/master/root/etc/services.d/radarr/run](url)
`exec \
	s6-setuidgid abc mono --debug Radarr.exe \
-nobrowser -data=/config`

Thank you for your work !

**Comment by sparklyballs** [comment]
radarr is a fork of sonarr and we were specifically asked by the sonarr team to enable debug mode on that image and we followed suit with this one.

unless they (radarr) advise us otherwise, it will stay in debug mode.

**Comment by Casper042** [comment]
Please Reconsider.
I just built a new Skylake Xeon box with 6 cores.
With LinuxServer/Radarr running it's 40% busy on all cores.
With LinuxServer/Radarr stopped, it drops to **4**% average on all cores.
4% includes containers for SAB, Portainer, ARKServer, Ombi, Bazarr and Plex.
So it's kind of ridiculous that Radarr by itself is using 35 % of a 6 core Xeon Scalable.

I haven't even deployed the Sonarr container and now I'm scared to.  
Might have to go back to Medusa and Couch Potato at this rate.

Is it possible for me to disable debug mode just on my copy of the container to see the impact?

**Comment by aptalca** [comment]
Are you restarting within the radarr gui?

**Comment by Casper042** [comment]
> Are you restarting within the radarr gui?

I had in the past, yes.

Looks like restarting the entire container makes it behave better.

Is that a known issue?

**Comment by aptalca** [comment]
Yeah, don't restart via gui, it launches multiple sessions and causes cpu spikes. Only restart the container

**Comment by Casper042** [comment]
I found it:
https://github.com/Radarr/Radarr/issues/3278#issuecomment-566087989
So I guess nevermind.
Looks like that was the source of my problem.
I've also limited Radarr to 1 CPU max so if I forget it doesn't do as much damage.

**Comment by aptalca** [comment]
With our docker containers, you shouldn't use the in app updates or restarts unless we tell you to do so. Otherwise they cause issues. Do the updates and power/state management through docker

**Comment by Casper042** [comment]
Yeah I had a bunch of warnings in the app right after first launch and config telling me my Indexer and Download Client weren't configured when they actually were, and I found the Restart option nearby so I just went ahead and did that to restart.
Live and Learn.
