### ISSUE TITLE
A lot of docker container upgrades

### ISSUE THREAD

**Issue by elmero1** [linuxserver/docker-radarr#103]
Almost every day I receive an update for the radarr container. Are these updates from linuxserver or from radarr?
I use the stable version.

**Comment by IronicBadger** [comment]
You can see the changelog for this container from the Linuxserver.io side in the `readme-vars.yml` file which is present the root of every repository.

```
# changelog
changelogs:
  - { date: "05.04.20:", desc: "Move app to /app." }
  - { date: "01.08.19:", desc: "Rebase to Linuxserver LTS mono version." }
  - { date: "13.06.19:", desc: "Add env variable for setting umask." }
  - { date: "10.05.19:", desc: "Rebase to Bionic." }
  - { date: "23.03.19:", desc: "Switching to new Base images, shift to arm32v7 tag." }
  - { date: "09.09.18:", desc: "Add pipeline build process." }
  - { date: "24.02.18:", desc: "Add nightly branch." }
  - { date: "06.02.18:", desc: "Radarr repo changed owner." }
  - { date: "15.12.17:", desc: "Fix continuation lines." }
  - { date: "17.04.17:", desc: "Switch to using inhouse mono baseimage, adds python also." }
  - { date: "13.04.17:", desc: "Switch to official mono repository." }
  - { date: "10.01.17:", desc: "Initial Release." }
```

Beyond that, you can view the CI pipeline at [ci.linuxserver.io](https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-radarr/) which will show you all Linuxserver builds of this container.

Furthermore you can also view tag history (to a point anyway) on Docker hub [here](https://hub.docker.com/r/linuxserver/radarr/tags).

**Comment by nemchik** [comment]
https://github.com/linuxserver/docker-radarr/releases

The version numbers are made up of two parts.

`app.ver`-`lsbuild`
So if you see `1.0.0-ls5` that means the version of the app is `1.0.0` and we have made 5 builds of the image that typically contain changes from us like dependencies, but when the app updated we also increase our build number. So `1.0.1-ls6` likely just means the new version of the app. After that `1.0.1-ls7` would contain changes from us (possibly dependencies, possibly changes to code that makes the container work).

They other thing to note is releases and pre-releases. If you're using the `preview` tag you only want to look at pre-releases. If you're using `latest` you only want to look at releases (not including pre-releases).

With that info you should be able to read into how often updates are released for the tag you're using and whether those updates are from the app updating or from us making changes or updating dependencies.

Free free to ask if you have any other questions.
