### ISSUE TITLE
Seems that Radarr has eliminated "aphrodite" build

### ISSUE THREAD

**Issue by Greg2dot0** [linuxserver/docker-radarr#106]
Latest pull of radarr image 'linuxserver/radarr:preview' indicated that the _aphrodite_ build was being sunseted and that you should switch to the nightly build. After switching this image to pull 'linuxserver/radarr:nightly' I now get the warning message:

**Please upgrade to the .NET Core version of Radarr**

**Comment by hotio** [comment]
We are aware (https://github.com/linuxserver/docker-radarr/pull/105), either switch back to `:preview` or wait
