### ISSUE TITLE
Hardlinks not working across volumes

### ISSUE THREAD

**Issue by hesdago** [linuxserver/docker-radarr#11]
Linuxserver.io version:- 44 Build-date:- June-02-2017-22:39:59-UTC on Fedora 25

Hi, since I'm quite new to this process, I tried to follow the general instructions from the readme when creating my container - as such I've first mounted my download and movies directory separately when using docker create:

    docker create \                                                                  
    --name=radarr \     
        -v /home/dago/.config/radarr:/config \ 
        -v /mydownloads:/downloads \
        -v /myMovies:/movies \
        -v /etc/localtime:/etc/localtime:ro \
        -e TZ=Europe/Berlin \     
        -e PGID=1006 -e PUID=1000 \
        -p 7878:7878 \
    linuxserver/radarr     `

However, using this setup prevents hardlinks from working with radarr, as my understanding is that it thinks that there are two different filesystems, and since hardlinks don't work across filesystems, it copies the entire movie file instead. 

As such I went back and recreated the container, making sure to include both myMovies and mydownloads in a single volume mount. This allows radarr to create hardlinks and save space. 

Now my issue is solved, and this is fine for my needs - but I guess other newcomers might be just as confused about this, so perhaps the default suggested docker create command should be either clarified for limitations, or adapted to allow hardlinks inside the container.

**Comment by sparklyballs** [comment]
we provide a general `get you started` style create line in the README as we can't be all things to everyone.

if users want to digress from that they can........
