### ISSUE TITLE
Custom Python scripts broken in nightly branch

### ISSUE THREAD

**Issue by daverof** [linuxserver/docker-radarr#112]
In a recent update of the nightly branch, the custom scripts feature in Radarr no longer supports Python scripts which breaks my custom post-processing scripts.

Can Python be added back to the image? If possible, now would be a good time to upgrade to Python 3.

Thanks and great work on this container.

**Comment by aptalca** [comment]
You can add python3 via a custom script: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
