### ISSUE TITLE
Permission denied error after latest update

### ISSUE THREAD

**Issue by paulr24** [linuxserver/docker-radarr#113]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
## Current Behavior
I believe this issue started after Watchtower attempted a nightly update. I am currently getting the errors in the logs below.
## Environment
**OS:** Synology DSM 6
**CPU architecture:** x86_64
**How docker service was installed:** From Docker registry: linuxserver/radarr:nightly
## Docker logs
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
foreground: warning: unable to spawn /docker-mods: Permission denied
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/10-adduser: Permission denied
[cont-init.d] 10-adduser: exited 127.
[cont-init.d] 30-config: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/30-config: Permission denied
[cont-init.d] 30-config: exited 127.
[cont-init.d] 99-custom-scripts: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/99-custom-scripts: Permission denied
[cont-init.d] 99-custom-scripts: exited 127.
[cont-init.d] done.
[services.d] starting services
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise radarr: warning: unable to spawn ./run - waiting 10 seconds
[services.d] done.
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise radarr: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied

**Comment by theg00s3** [comment]
I'm also getting this error with the latest update

**Comment by theg00s3** [comment]
Downgrading to linuxserver/radarr:version-3.0.0.3987 is a temporary fix

**Comment by Deuxgod** [comment]
I can confirm that the same thing happened with all my radarr containers

**Comment by hellcry37** [comment]
same

**Comment by aptalca** [comment]
This is fixed in the latest build pushed earlier

**Comment by Dubwize** [comment]
+1 -  Same issue here.
