### ISSUE TITLE
Please add a bionic tag for radarr on armv7l

### ISSUE THREAD

**Issue by offbyone** [linuxserver/docker-radarr#123]
## Expected Behavior
radarr should start on my Raspberry Pi

## Current Behavior
It does not :)

Looking at https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal I see that I am getting the same date symptom as described there:

```
❯ docker exec radarr date
Fri 20 Feb 1970 08:21:15 PM UTC
```

My pi has this architecture: 
```
❯ uname -a
Linux torrents 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
```

The service doesn't appear to be running inside the container:

```
❯ docker exec radarr ps -ewwf
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0  2020 ?        00:00:00 s6-svscan -t0 /var/run/s6/services
root        34     1  0  2020 ?        00:00:00 s6-supervise s6-fdholderd
root       255     1  0  2020 ?        00:00:01 s6-supervise radarr
root      4012     0  0  2020 ?        00:00:00 ps -ewwf
```

## Environment
**OS:** Raspbian
**CPU architecture:** armv7l
**How docker service was installed:** Via the geerlingguy ansible role

```
docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:35:24 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:22 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Command used to create docker container (run/create/compose/screenshot)
Via compose file:
```
version: '3.7'
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: always
    ports:
      - "127.0.0.1:8310:8310"
      - "8311:8311"
    volumes:
      - /etc/radarr:/config
      - /mnt/media:/media:rw
    environment:
      - PGID=1000
      - PUID=1000
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by Roxedus** [comment]
We can't. We would not use focal unless we have to. For plex and jellyfin, using bionic would just not let you use certain features.

What version of libseccomp2 do you actually have?

**Comment by offbyone** [comment]
```
Package: libseccomp2
Version: 2.3.3-4
Priority: optional
Section: libs
Source: libseccomp
Maintainer: Kees Cook <kees@debian.org>
Installed-Size: 161 kB
Depends: libc6 (>= 2.4)
Homepage: https://github.com/seccomp/libseccomp
Download-Size: 33.1 kB
APT-Manual-Installed: yes
APT-Sources: http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
Description: high level interface to Linux seccomp filter
 This library provides a high level interface to constructing, analyzing
 and installing seccomp filters via a BPF passed to the Linux Kernel's
 prctl() syscall.
```

(I'm gonna be at work today, so I can follow up with troubleshooting late tonight)

**Comment by Roxedus** [comment]
You have to do one of the approaches in the wiki, to get a up-to-date package

**Comment by offbyone** [comment]
Sounds good, thanks!

**Comment by allenbina** [comment]
I'm having the same issue.  Can you link to the wiki please.

**Comment by grota** [comment]
Same here I tried with both libseccomp2_2.4.4-1~bpo10+1_armhf and libseccomp2_2.5.0-3_armhf, rebooted but still did not work.

**Comment by Roxedus** [comment]
2.5 does not have the patch, 2.5.1 might. 

@allenbina @grota What OS' are you guys using?

**Comment by allenbina** [comment]
While responding to this, I restarted the container to get a clean set of logs and it worked.  I'm not sure what I did to fix it, but I believe that those two packages might have fixed it, and I needed to restart or something.  To install, I used the docker-cli run command:

docker run -d \
  --name=radarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e UMASK_SET=022 `#optional` \
  -p 7878:7878 \
  -v /path/to/data:/config \
  -v /path/to/movies:/movies \
  -v /path/to/downloadclient-downloads:/downloads \
  --restart unless-stopped \
  ghcr.io/linuxserver/radarr

$cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:21:06 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:19:00 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by afonsof** [comment]
Guys same problem here.
When I enter inside the container and try to run Radarr manually using '/app/radarr/bin/Radarr' I get this error: `Aborted (core dumped)`.

**Comment by j0nnymoe** [comment]
@afonsof do the fix?

**Comment by offbyone** [comment]
As "doing a bionic tag" on Radarr isn't tractable according to the devs, and since my issue is solved by their existing instructions, as well, I'm closing this. Thanks, team, I appreciate the help!

**Comment by afonsof** [comment]
> @afonsof do the fix?

It's not clear for me what is the fix. Which libraries do I need to install?

**Comment by grota** [comment]
sorry guys for the late reply, I'm leaving here a workaround, since installing the suggested updated libseccomp2 package did not solve the issue for me.
I am also on `Raspbian GNU/Linux 10 (buster)` but with an earlier docker version:

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Fri, 13 Sep 2019 10:45:43 +0100
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Fri Sep 13 09:45:43 2019
  OS/Arch:          linux/arm
  Experimental:     false
```
 The workaround for me was to use an older image tag: `linuxserver/radarr:arm32v7-version-v0.2.0.1504`

**Comment by aptalca** [comment]
`I am also on Raspbian GNU/Linux 10 (buster) but with an earlier docker version:` Then update your docker?

Radarr v3 does not work on the bionic baseimage, you'll have to fix your host environment.

**Comment by grota** [comment]
for some odd reason (that right now I don't want to investigate) even after an apt update I only see `18.09.1+dfsg1-7.1+rpi1+rpt1` `18.09.1+dfsg1-7.1+rpi1+deb10u2` as versions available for the docker.io package. Thanks for the info about v3, debugging and resolving the upgrade issue is an issue for future me :)

**Comment by aptalca** [comment]
We recommend installing docker from the official repos: https://docs.docker.com/engine/install/debian/
Alternatively, you can try the convenient get docker script: https://get.docker.com/
