### ISSUE TITLE
Unable to access API from outside container using new .NET based version

### ISSUE THREAD

**Issue by mrlindstrom** [linuxserver/docker-radarr#124]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
API should be accessible

## Current Behavior
From SABNZBd:
Radarr: Failed to post-process - Radarr did not respond.!

Logs from Radarr:
2020-12-8 09:10:42.2|Info|Auth|Auth-Unauthorized ip ::ffff:10.0.3.1 url 'http://127.0.0.1:7878'

## Steps to Reproduce
1. Run new .NET based Radarr in docker
2. Attempt to access Radarr api from outside container

## Environment
OS: QNAP Container Station
CPU architecture: x86_64
How docker service was installed: Container station using docker repo

## Command used to create docker container (run/create/compose/screenshot)
Followed guide at: https://blog.linuxserver.io/2017/09/17/how-to-setup-containers-on-qnap/

## Docker logs
Full logs need to be sanitized but the relevant part is below:

[Info] Auth: Auth-Unauthorized ip ::ffff:10.0.3.1 url 'http://127.0.0.1:7878'
[Info] Auth: Auth-Unauthorized ip ::ffff:10.0.3.1 url 'http://127.0.0.1:7878'

## Other notes
Not sure if this is relevant but seemed possible: https://github.com/dotnet/aspnetcore/issues/17081#issuecomment-553741407

**Comment by aptalca** [comment]
It works fine here. It's either a misconfiguration or an upstream issue

**Comment by mrlindstrom** [comment]
It decided it wanted to respond now.... I tried it from my machine before and it wouldn't ever respond. Closing issue.

**Comment by jzahraoui** [comment]
I'm having the same problem.
runing latest docker imageon linux debian, my system informations  :
```

uname -vrs
Linux 5.10.0-5-amd64 #1 SMP Debian 5.10.24-1 (2021-03-19)

docker -v
Docker version 20.10.5+dfsg1, build 55c4c88

head /opt/radarr/logs/radarr.txt
2021-4-10 14:44:32.9|Info|Bootstrap|Starting Radarr - /app/radarr/bin/Radarr.dll - Version 3.0.2.4552

tail /opt/radarr/logs/radarr.txt
2021-4-14 20:54:47.5|Info|Auth|Auth-Unauthorized ip ::ffff:172.17.0.1 url 'http://localhost:8089/api/command'


```
any help will be appreciates
