### ISSUE TITLE
Core dump on armhf Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by frankicia** [linuxserver/docker-radarr#128]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After starting the container, the webui should load.

## Current Behavior
After updating the image, the webui doesn't load when running the container. Trying to run radarr within the container fails with: "Aborted (core dumped)"

## Steps to Reproduce
1. docker run -d   --name=radarr   -e PUID=1000   -e PGID=1000   -e TZ=Europe/Madrid   -p 7878:7878   -v /home/cortega/radarr:/config   -v /mnt/Storage/Movies:/movies   -v /mnt/Storage/Torrents/:/downloads   --restart unless-stopped   linuxserver/radarr

## Environment
**OS:** Ubuntu 18.04.5 LTS
**CPU architecture:** arm32 (armv7l)
**How docker service was installed:** official docker repo

## Command used to create docker container (run/create/compose/screenshot)
docker run -d   --name=radarr   -e PUID=1000   -e PGID=1000   -e TZ=Europe/Madrid   -p 7878:7878   -v /home/cortega/radarr:/config   -v /mnt/Storage/Movies:/movies   -v /mnt/Storage/Torrents/:/downloads   --restart unless-stopped   linuxserver/radarr

## Docker logs
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
Radarr: https://opencollective.com/radarr,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
Radarr: https://opencollective.com/radarr,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,

**Comment by Roxedus** [comment]
Did you look at the list of possible fixes? https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal

**Comment by j0nnymoe** [comment]
As mentioned in the other issue. This is not an issue with the container but an issue with your host. Look at the list of fixes mentioned above.

**Comment by frankicia** [comment]
Fixes mentioned above do not work in my platform.

```
$  sudo apt install -t buster-backports libseccomp2
libseccomp2 is already the newest version (2.4.4-1~bpo10+1).
```

**Comment by Roxedus** [comment]
Does it have the same date symptom?

**Comment by frankicia** [comment]
It does, yes.
But I'm not using a raspberry nor Raspbian OS.

**Comment by Roxedus** [comment]
What you run doesnt really matter, its just common on those platforms. Take it you restarted the container after updating libseccomp?

**Comment by frankicia** [comment]
Yes, and deleted it and create it again. Didn't work.

**Comment by aptalca** [comment]
`But I'm not using a raspberry nor Raspbian OS.`
Then list what you're using and what you tried (compose, yaml, docker run, etc.) and the logs

**Comment by frankicia** [comment]
> `But I'm not using a raspberry nor Raspbian OS.`
> Then list what you're using and what you tried (compose yaml, docker run, etc.) and the logs

I did in the first post:
OS: Ubuntu 18.04.5 LTS
CPU architecture: arm32 (armv7l)
How docker service was installed: official docker repo
Using docker run. Log is in the first post as well. Logs seem fine, but Radarr aborts with a core dump when executed.

**Comment by j0nnymoe** [comment]
What's the device?

**Comment by frankicia** [comment]
> What's the device?

Odroid XU4

I tried to create the container with --privileged, and it works. Does anybody the reason behind this?

**Comment by Roxedus** [comment]
The reason why --privileged work? pretty sure thats because it bypasses the check that libseccomp does. Do you by chance have multiple versions of it installed?

**Comment by frankicia** [comment]
> The reason why --privileged work? pretty sure thats because it bypasses the check that libseccomp does. Do you by chance have multiple versions of it installed?

I do, indeed.
```
$ apt list -a libseccomp2
Listing... Done
libseccomp2/now 2.5.1-1 armhf [installed,local]
libseccomp2/buster-backports 2.4.4-1~bpo10+1 armhf
libseccomp2/bionic-updates,bionic-security 2.4.3-1ubuntu3.18.04.3 armhf
libseccomp2/bionic 2.3.1-2.1ubuntu4 armhf
```

When I try to select a specific one, fails:
```
$ sudo update-alternatives --list libseccomp2
update-alternatives: error: no alternatives for libseccomp2
```

I tried to remove all but one version, but apt tries to remove other several packages including apt.

**Comment by Roxedus** [comment]
Libseccomp releases confuse me. Is it clear for you to determine if 2.5.1 does have the aarch64 patch that 2.4.4 have? It makes me believe it isn't. https://github.com/seccomp/libseccomp/releases

**Comment by frankicia** [comment]
> 
> 
> Libseccomp releases confuse me. Is it clear for you to determine if 2.5.1 does have the aarch64 patch that 2.4.4 have? It makes me believe it isn't. https://github.com/seccomp/libseccomp/releases

This is the manually installed with dpkg -i. I don't know how to check if it has the patch. Should I remove it?

**Comment by Roxedus** [comment]
I would try that, yea

**Comment by frankicia** [comment]
Still not working:

```
$ apt list -a libseccomp2
Listing... Done
libseccomp2/buster-backports,now 2.4.4-1~bpo10+1 armhf [installed]
libseccomp2/bionic-updates,bionic-security 2.4.3-1ubuntu3.18.04.3 armhf
libseccomp2/bionic 2.3.1-2.1ubuntu4 armhf
```
After installing the libseccomp2 recommended to fix the problem, I still have issues.
I restarted and deleted and created the docker again, still not working. Any ideas?
