### ISSUE TITLE
Radarr 3.0.x doesn't remover torrent from Transmission

### ISSUE THREAD

**Issue by mada199122** [linuxserver/docker-radarr#129]
Hi,
since I've upgraded from 5.14 momo version to 3.0.x branch (I've tried all the three latest, develop and nightly version), Radarr doesn't remove anymore complete seeded torrent from Transmission.
I haven't changed anything from my configuration just upgraded. Before Radarr has always removed correctly all the torrent.
Could you have a look please?
Thanks

**Comment by mada199122** [comment]
the issue template link doesn't work.
Do you need other info to track the bug?

**Comment by j0nnymoe** [comment]
I mean, this would be an issue with radarr itself, not an issue the with container. We just package the upstream releases.
