### ISSUE TITLE
Request: Support for tags for switch between different branches

### ISSUE THREAD

**Issue by desimaniac** [linuxserver/docker-radarr#13]
Hi Team linuxserver.io.

Can we add tags to choose between various branch versions of Radarr (especially Nightly branch), similar to the way you have it for [Sonarr](https://github.com/linuxserver/docker-sonarr)?

They only have two main branches: Develop and Nightly.

**Comment by sparklyballs** [comment]
radarr is under heavy development and we install the latest version in their release section on GitHub 

nightlies are covered by another docker image from hotio listed on the radarr GitHub page
