### ISSUE TITLE
Unable to view radarr WebUI on Raspberry Pi 4

### ISSUE THREAD

**Issue by JoshLoecker** [linuxserver/docker-radarr#131]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When I start the radarr container with `docker-compose up -d` it should start radarr. I should then be able to view the web interface at `http://ip-address:7878`. Config files should be populated under the folder bound to `/config` in the docker-compose file.
## Current Behavior

When I start the radarr container with `docker-compose up -d`, the container is pulled from docker hub, and it appears to start correctly. However, when I go to the folder bound to `/config`, no files are present. I am unable to view the web interface at `http://ip-address:8080`.
## Steps to Reproduce

1. Remove all previous data within docker pertaining to radarr
2. `docker stop radarr`
3. `docker rm radarr`
4. `docker rmi <radarr-image>`
5. Start the container with `docker-compose up -d`

It is at this point the container appears to start, but no files are present in the `/config` section, after running `docker exec -it radarr /bin/bash`. Additionally, I am unable to run `curl ifconfig.me` from within the container. I get the error `curl: (28) Timeout was reached`.

## Environment
**OS:** DietPi v6.34.3
**CPU architecture:** armv7l
**How docker service was installed:**
Docker was installed through the DietPi interface `dietpi-software`. Docker compose was installed with `pip3 install docker-compose`.

## Command used to create docker container (run/create/compose/screenshot)

[Relavent docker-compose section here](https://pastebin.com/NJfdQCx8)

## Docker logs

[`docker logs radarr` here](https://pastebin.com/j4PUkk8f)

**Comment by j0nnymoe** [comment]
Solution here: https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal

**Comment by JoshLoecker** [comment]
Thank you for the speedy response! I wasn't aware of this
