### ISSUE TITLE
Radarr V3 Folder is not writable by user abc

### ISSUE THREAD

**Issue by Danpoulter97** [linuxserver/docker-radarr#132]
I have newly setup a docker container for Sonarr and Radarr. Sonarr is working perfectly with the same base config and permissions but Radarr always errors when adding a root folder.
I can add a folder manually where I am trying to set the root folder with the same user (1001) but Radarr wont add the path.

I have tried making the abc user the owner of that folder but that made no difference. 

The container was made with PUID=1001 and  PGID=1001

Is anyone else having this issue?

My build is Docker 19.03.12 on linux, amd64
Radarr is version:- 3.0.1.4259

**Comment by mitch98** [comment]
I'm also having the same issue, using a Raspberry Pi 4 on OpenMediaVault. Same issue occurs on a Pi 3 (latest RaspberryPiOS, running docker stand-alone without OpenMediaVault). Sonarr is working fine.

**Comment by mitch98** [comment]
> I'm also having the same issue, using a Raspberry Pi 4 on OpenMediaVault. Same issue occurs on a Pi 3 (latest RaspberryPiOS, running docker stand-alone without OpenMediaVault). Sonarr is working fine.

Update: Looks like this is a known issue - https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal

Following the steps outlined above resolved the issue for me Danpoulter97

**Comment by Roxedus** [comment]
@Danpoulter97 Did you look at the entry above?

**Comment by thomasvvugt** [comment]
I'm having the same issue.
Running docker 20.10.5 on Ubuntu Focal (20.04.2 LTS), and I tried option 3 in the link mentioned above.

However, still getting the error (both on PUID/PGID 1000 and 0);
[Warn] RadarrErrorPipeline: Invalid request Validation failed: 
 -- Path: Folder is not writable by user abc

**Comment by phatphillips** [comment]
I had this issue running omv running unionfs and snapraid - for some reason the user group didn't have permissions to the Movies and TV-Shows directory. 
All I had to do to fix this was `chmod -R g+rwx /path-to-movies/or/tv-shows/` No need to restart the container, it should just work.

**Comment by Cromm** [comment]
I had this issue running radarr on osx using remote folders mounted using samba. When I changed to AFP the problem went away. I hope this helps others!

**Comment by eduzen** [comment]
Same issue here, rest of linuxserver images with puid and guid are working fine, but not radarr

**Comment by eduzen** [comment]
Not a real solution, but it's possible to do:

```
docker-compose exec radarr bash

$ chown 1000:1000 /movies -R
```
To be able to add a Root Folders

**Comment by DonHansDampf** [comment]
Had the same problem on DSM 7 with the latest built. PUID/GUID was set but still a mounted volume was not writeable. Inside the container the mounted /movies folder hat simply broken access rights (no rwx for anyone -> 000).

Fixing the access rights (`chmod -R 0770 /movies`) solved the problem for now. But how did this happen?

**Comment by j0nnymoe** [comment]
Without providing any info on how you all have deployed the container on Synology, the only thing we can assume is it's been deployed incorrectly and whatever user you have it running as doesn't have the required permissions.

**Comment by DonHansDampf** [comment]
@j0nnymoe Deployed the container via the Synology Docker GUI Interface. 

Added 3 volumes (config, Download and Movies). Config and Download are writeable without any issues.

Only added Environment Variables are TZ (Europe/Berlin), PUID (like the user on the synology host with write access to the folders) and PGID. Also published the port. Nothing else was changed.

Used the latest docker image from the repository. Resetting the container (or creating it completly new) didn't fix the problem.

```json
{
   "CapAdd" : null,
   "CapDrop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : true,
   "entrypoint_default" : "/init",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "LANGUAGE",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "LANG",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "XDG_CONFIG_HOME",
         "value" : "/config/xdg"
      },
      {
         "key" : "TZ",
         "value" : "Europe/Berlin"
      },
      {
         "key" : "PGID",
         "value" : "100"
      },
      {
         "key" : "PUID",
         "value" : "1026"
      }
   ],
   "exporting" : false,
   "id" : "b704bf8d318d81ab2fcd9723b18d3ba8ca1b72e8d4d4f6d595b2cda51c4cde46",
   "image" : "linuxserver/radarr:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "linuxserver-radarr1",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 7878,
         "host_port" : 7878,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/media/Movie",
         "mount_point" : "/movies",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/config/radarr",
         "mount_point" : "/config",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/download/Radarr-DL",
         "mount_point" : "/downloads",
         "type" : "rw"
      }
   ]
}

```

**Comment by alexcom** [comment]
@j0nnymoe Maybe permissions were not that broken. The directory mounted brought host file system permissions and ownership inside container with it. I just was resolving the same issue.
Synology DSM 7, Docker, linuxserver/radarr:latest
I executed interactive shell to look inside the container and I saw that `movies` and `downloads` directories have ownership `1024:users`. So at least user is incorrect. I check host filesystem and indeed directories belonged to `admin`(UID=1024) user while UID I passed into configuration was of my second user `alexcom`. chown to correct user and consecutive chmod fixed the problem. It does not matter where you execute these commands, inside container or on host filesystem.

**Comment by adx74** [comment]
Hello, same issue here, but all of your commands never change something, PID and UID set as 1000 like my user.
Any solutions please ?

Radarr version : 3.0.6.1342
Package Version: 3.0.6.1342-ls132 by linuxserver.io
On Linux 20.04 LTS AMD64

Thanks in advance

**Comment by nmfreitas** [comment]
Hi, same issue here.

Have a PC running Ubuntu 20.04 LTS and Docker , plus Synology NAS DS215J

When installing Sonarr or Radarr, have the issue.

![image](https://user-images.githubusercontent.com/86863705/156897772-82e9acf6-6a6c-47ca-94c9-145868e1a72a.png)
This is the folders in Synology all have chmod 777 (for tests only)

![image](https://user-images.githubusercontent.com/86863705/156897821-1a2345c7-2c69-4f8e-a27d-954b23407ac8.png)
This is the same folders mounted in the PC via SMB.
Cant change the permission level. 

When i try to add a "ROOT FOLDER" both on radarr and sonarr this issue happens. 

The PUID and PGID are 1000 both on docker-compose and in the system. 
Tried create a user "abc" and change the PUID and PGID for the respective user, and didnt work.

Is the problem on the synology, the share folder, docker or the apps?

Thanks

**Comment by j0nnymoe** [comment]
Edited you post to remove the copyrighted content. But clearly showed via your SMB mount that the ownership of the files are incorrect. Your mounts need to be done as the same user you're running the containers as. 

That's the issue for all here, it's specific to your remote mounts, not a container issue. 

Closing this issue as its not designed for general support, our discourse and discord is best for that.

**Comment by j0nnymoe** [comment]
Also, I'm aware that users here have had the same error but different setups, if you do still feel your issue is to with the container, please open a fresh issue and provide all the requested information in the template.

**Comment by rajivravio** [comment]
> I had this issue running omv running unionfs and snapraid - for some reason the user group didn't have permissions to the Movies and TV-Shows directory. All I had to do to fix this was `chmod -R g+rwx /path-to-movies/or/tv-shows/` No need to restart the container, it should just work.
> 
> Edit: I was rebuilding my docker containers.. I ran into this issue again - this time I had a different but same issue. I had to run as root `chown username /path-to-movies/or/tv-shows/` then `chmod -R g+rwx /path-to-movies/or/tv-shows/` then `chomd -R 777 /path-to-movies/or/tv-shows/` Also i used `ls -ltr /path-to-movies/or/tv-shows/` to figure out which group and user owns what. Hopefully this helps some poor soul out there

Thank you sir!

**Comment by geekykant** [comment]
Had the same issue when downloading to mounted storage, folder permissions weren't changing. Solved by setting the sonarr docker container env PUID and  PGUID to `0`, which is basically root permission.
```
environment:
      - PUID=0
      - PGID=0
```

**Comment by Mr-Quinn** [comment]
setting the guid=use_name and puid=0 in fstab
then the credential file username=xyx, password=xxxxx

sudo mount -a and we're good!
