### ISSUE TITLE
Branch 'aphrodite' has been merged, switch to 'nightly' for further V3 development

### ISSUE THREAD

**Issue by duelistjp** [linuxserver/docker-radarr#136]
---
name: Switch branch of radarr to current branach
about: the aphrodite branch of radarr is no longer in development and i can't seem to switch branches in settings

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Switch to the current branch of radarr please or tell me how i can change this. when i got to settings myself the branch can't be changed and the settings file in opt/appdata seems to change itself back if i change it their
------------------------------

## Desired Behavior
Use the nightly build

## Current Behavior
Uses the aphrodite build

## Alternatives Considered
not using docker.  can't switch the branch inside the docker.  hasn't been updated since september.

**Comment by Roxedus** [comment]
?????

Do you use docker or not? If you do, fill the issue template.

**Comment by duelistjp** [comment]
sorry did not realize it would format itself nicely so had tred to cut out the unneccessary parts. will post the template presently

**Comment by Roxedus** [comment]
There is still key information missing.

**Comment by duelistjp** [comment]
what information is needed.  i thought it looked like i filled out the template.

**Comment by Roxedus** [comment]
The *bug* template asks for: 
OS:
CPU architecture: x86_64/arm32/arm64 
How docker service was installed:
Command used to create docker container (run/create/compose/screenshot):
Docker logs:

**Comment by duelistjp** [comment]
i thought this would be a feature request to switch the branches did not realize it was a bug.
lubuntu 20.10
x86_64
not sure what you mean by how the service was installed
the docker-compose file i've played with a bit trying to get the branch switched but here is what the section currently is 
radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/StoragePool:/mnt/StoragePool
      - /opt/appdata/letsencrypt/etc/letsencrypt/:/le-ssl
      - /mnt/Torrent:/mnt/Torrent
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1002
    restart:
      unless-stopped

not sure where to get the logs you want

**Comment by Roxedus** [comment]
We switched over ages ago, so the feature you asked about is already done, the bug is that you are still seeing it. What build are you on? `docker inspect -f '{{ index .Config.Labels "build_version" }}' radarr`

**Comment by duelistjp** [comment]
Linuxserver.io version:- 3.0.0.3790-ls31 Build-date:- 2020-11-24T09:27:41+00:00

**Comment by Roxedus** [comment]
Your build is 2 months old, please update

**Comment by duelistjp** [comment]
That is what I'd been trying to do.  don't know why but this time i shut it down moved the config file.  let it recreate it then shut is down again and moved it back and restarted and this time it seems to have worked.  don't know why it hadn't worked the last several times i had tried to shut the docker down and restart

**Comment by DavidFW1960** [comment]
You need to switch the image to
ghcr.io/linuxserver/radarr:nightly
As per the readme
This changed a few months ago

**Comment by Roxedus** [comment]
> You need to switch the image to
> ghcr.io/linuxserver/radarr:nightly
> As per the readme
> This changed a few months ago

No. This is incorrect. We push to both registries, a docker pull should suffice.

**Comment by duelistjp** [comment]
had tried numerous times but this afternoon seemed to finally work. don't know exactly why
