### ISSUE TITLE
All Files Going To QBittorrent Default Directory

### ISSUE THREAD

**Issue by FatSandwich** [linuxserver/docker-radarr#139]
No matter what directory I set in radarr it would always go to the default QBittorrent directory ( **/downloads** )
I want it to go to the **/movies** directory, but it wouldn't work.

In the system settings it says:
You are using docker; download client QBittorrent places downloads in **/Users/.../Movies** ( **/movies** directory ) but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.

Radarr Docker-Compose:
---
version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Users/.../radarr/Config:/config
      - /Users/.../Movies:/movies
      - /Users/.../Movies/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

**Comment by aptalca** [comment]
Not a bug, you can drop by our discord or discourse for general support
