### ISSUE TITLE
Manual Category Options for Indexers

### ISSUE THREAD

**Issue by bmarohl** [linuxserver/docker-radarr#140]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Working with non standard categories on various indexing sites isn't possible. Current case is with www.gingadaddy.com. These are their movie and tv catagories:
85,45,42,48,51,54,60,69,66,72,67,75

I'd like a custom button so catagorie numbers could be manually entered.

## Current Behavior
Manual entry isn't an option, the catagories can't be sensed, the non standard sites can't be saved because they can't locate catagories and won't allow save without at least 1 selected.

## Alternatives Considered
I would just like some form of manual entry for cases like this.

**Comment by Roxedus** [comment]
This is a Radarr issue, not a container issue. https://github.com/Radarr/Radarr is the place you want.
