### ISSUE TITLE
radarr app throws segmentation fault

### ISSUE THREAD

**Issue by ifeghali** [linuxserver/docker-radarr#147]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

container should start and web gui accessible

## Current Behavior

container starts but Web GUI is not accessible. deeper investigation reveals radarr app is throwing a segmentation fault and re spawning forever. Device is WD MyCloud EX2 Ultra. Other linuxserver containers (such as sonarr, bazarr etc.) runs just fine in the same environment.

## Steps to Reproduce
1. install docker app in NAS
2. pull radarr image and create container
3. start container
4. open a container shell 
5. watch ps -ef (note radarr proccess re spawning)
6. remove radarr s6 service
7. kill s6-supervise for radarr
8. manually start radarr and note segmentation fault

## Environment
**OS:** Linux 4.14.22-armada-18.09.3 ga-18.09.3 arm7l + MyCloud OS5
**CPU architecture:** arm32
**How docker service was installed:**

WD-community docker native app + custom build of docker 20.10.8 binaries (binaries provided with community app was throwing error about libseccomp so the updated binaries were necessary to make use of kernel's embedded seccomp in OS5).

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d \
  --name=radarr \
  -e PUID=1007 \
  -e PGID=1007 \
  -e TZ=America/Sao_Paulo \
  -p 7878:7878 \
  -v /shares/Volume_1/Nas_Prog/radarr/config:/config \
  -v /shares/Public/Movies:/movies \
  -v /shares/Public/Downloads:/downloads \
  --restart unless-stopped \
  linuxserver/radarr
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------
To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/

-------------------------------------
GID/UID
-------------------------------------
User uid:    1007
User gid:    1007
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by newsmilec2d** [comment]
I am also getting the same issue. With same docker version 20.10.8 on WDCloudEx2Ultra NAS ARM base processor

**Comment by bakerboy448** [comment]
armada is not supported by dotnet

this is not a container issue
