### ISSUE TITLE
AMD Container not starting the service

### ISSUE THREAD

**Issue by waqasghouri89** [linuxserver/docker-radarr#148]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Radarr service should be execute and running, also generate the files in config folder.

## Current Behavior
Current Behavior is that Radarr service not working, when the docker container start it shows some logs but after starting service it gives an error no such file or directory bash

## Steps to Reproduce
I'm currently trying to build it on WDCloudEx2Ultra with Docker support with the following command 
`docker run -d \
-p 7878:7878 \
--name radarr \
--security-opt seccomp=unconfined \
--platform armhf \
--restart unless-stopped \
-e PUID=0 \
-e PGID=0 \
-e TZ=Europe/London \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/config/:/config \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/Downloads/:/downloads \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/Movies/:/movies \
ghcr.io/linuxserver/radarr
`
but no luck. 
Then I tried to clone the repository on Windows 10 x64 with Docker Desktop to make a image with the following command
` docker build --platform=armhf --no-cache --tag=myradarrnewarm .`
and then point this image in a docker-compose.yml file manually
`version: "2.1"
services:
  myradarr:
    container_name: myradarr
    #build: ./Dockerfile.armhf
    image: myradarrnewarm:latest
    volumes:
      - ./settings/config/.:/config
      - ./settings/Downloads/.:/downloads
      - ./settings/Movies/complete:/movies/complete
      - ./settings/Movies/incomplete:/movies/incomplete
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 7878:7878
    networks:
      - streaming
networks:
  streaming:
    driver: "bridge"`

and after container started it gives the same error which I am getting on WDCloudEx2Ultra Docker
I had generated the docker image with `--platform armhf` command 
The error I am getting both Docker Desktop (Windows 10) & Docker (WDCloudEx2Ultra SSH Docker)
![image](https://user-images.githubusercontent.com/6640637/135402498-912096bb-6fef-4d0d-ad2f-c34c7c53ec23.png)

## Environment
**OS:** `$ uname -a`
> Linux MyCloudEX2Ultra 4.14.22-armada-18.09.3 #1 SMP Mon Dec 21 02:42:49 UTC 2020 ga-18.09.3 Build-24 armv7l GNU/Linux
**CPU architecture:** arm

**How docker service was installed:**
on WDCLoudEx2Ultra I installed it with it compiled Package and Portainer is working on it successfully, I've also installed Sonarr on it and Jacket
![image](https://user-images.githubusercontent.com/6640637/135403139-3993adb3-637a-4a40-b5ad-edd2222eda77.png)

## Command used to create docker container (run/create/compose/screenshot)
> On WDCLoud Ex2 Ultra

``docker run -d \
-p 7878:7878 \
--name radarr \
--security-opt seccomp=unconfined \
--platform armhf \
--restart unless-stopped \
-e PUID=0 \
-e PGID=0 \
-e TZ=Europe/London \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/config/:/config \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/Downloads/:/downloads \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/Movies/:/movies \
ghcr.io/linuxserver/radarr`

> On Windows 10 Docker Desktop & Docker Compose 

`git clone https://github.com/linuxserver/docker-radarr.git`
cd into directory 
` docker build --platform=armhf --no-cache --tag=myradarrnewarm .` 
create new docker-compose.yml file in same directory where Dockerfile.armhf file exist
`version: "2.1"
services:
  myradarr:
    container_name: myradarr
    #build: ./Dockerfile.armhf
    image: myradarrnewarm:latest
    volumes:
      - ./settings/config/.:/config
      - ./settings/Downloads/.:/downloads
      - ./settings/Movies/complete:/movies/complete
      - ./settings/Movies/incomplete:/movies/incomplete
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 7878:7878
    networks:
      - streaming
networks:
  streaming:
    driver: "bridge"`
![image](https://user-images.githubusercontent.com/6640637/135403864-465e4afe-f362-4e0e-8fa8-ae3c260b8497.png)
    
`docker-compose -f docker-compose.yml up -d --build`

## Docker logs
![image](https://user-images.githubusercontent.com/6640637/135403939-886c050a-d11b-4a13-bea2-9345f1a3b4eb.png)

The same thing is working file on WDCLoudEx2Ultra and Windows 10 (Docker Desktop) with [Sonar](https://github.com/linuxserver/docker-sonarr)

**Comment by waqasghouri89** [comment]
I tried my all efforts and in the last I am opening this as a bug, I hope I'll get the support from developers. might be I'm doing wrong something, but same thing is working fine with Sonarr as document suggest the PID PGID all set to 0 (root)

**Comment by Roxedus** [comment]
We do not recommend passing 0 as the ID. 


Have you tried specifying the armhf tag on your run, as it seems it can't find the correct manifest?

**Comment by connect2d** [comment]
Yes, I tried by armhf build with the following command 
`docker build --platform=armhf --no-cache --tag=myradarrnewarm .`

**Comment by waqasghouri89** [comment]
Yes, I tried by armhf build with the following command
`docker build --platform=armhf --no-cache --tag=myradarrnewarm .`

**Comment by waqasghouri89** [comment]
Is there a way to find why its not able to find the manifest files ?

**Comment by aptalca** [comment]
Manifest files are used when you pull the image and create a container from it.

What you're trying to do is build an image. And you're doing it incorrectly (using the x86_64 Dockerfile to build an arm image).

I suggest simply following our readme and using either the docker run command or the compose yaml snippet to create a container. Don't overthink it.

**Comment by waqasghouri89** [comment]
oky, I'm going to try it again

**Comment by waqasghouri89** [comment]
I have tried

```
docker run -d \
-p 7878:7878 \
--name radarr \
--restart unless-stopped \
-e PUID=1002 \
-e PGID=1002 \
-e TZ=America/Toronto \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/config/:/config \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/Downloads/:/downloads \
-v /mnt/HD/HD_a2/Nas_Prog/_docker/volumes/streaming/_data/Movies/:/movies \
linuxserver/radarr:arm32v7-latest
```
As you suggested I tried with user abc PID=1002 && GUID=1002 but still my service not started.
it still stuck at 

```
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] files found in /config/custom-cont-init.d executing
[custom-init] 30-config: executing...
[custom-init] 30-config: exited 0
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
I manually put `run` file in config/custom-service.d/ folder but then I got the issue, no such file or directory issue but the file /app/radarr/bin/Radarr exist

**Comment by waqasghouri89** [comment]
I don't know the same way linuxserver/sonarr:latest is working fine no any user permission issue but don't understand whats wrong with Radarr tried with both linuxserver/radarr:latest & linuxserver/radarr:arm32v7-latest

**Comment by aptalca** [comment]
> I manually put run file in config/custom-service.d/ folder but then I got the issue, no such file or directory issue but the file /app/radarr/bin/Radarr exist

Stop doing additional manual steps. All you need is the run command. Stop and remove the container. Recreate following only our instructions, nothing more. Then post `full logs` (including the lsio banners) and tell us what happens.

**Comment by waqasghouri89** [comment]
Ok, I follow the same command as per documentation and here is the logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         (),
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io,
-------------------------------------

To support the app dev(s) visit:,
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:,
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID,
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services.
[services.d] done.
```

Thats all everything in a logs

**Comment by j0nnymoe** [comment]
Apart from running as root (0) - those logs are normal as expected.

**Comment by wg-connect2ddentistry** [comment]
I tried with another user with PID=500 & PGID=1000 but same result 
few users in my WDCLoud Ex2 Ultra

```
root@MyCloudEX2Ultra ~ # cat /etc/passwd
root:x:0:0:Linux User,,,:/home/root:/bin/sh
sshd:x:0:0:Linux User,,,:/home/root:/bin/sh
admin:x:500:1000:,,,,:/home/admin:/bin/sh
nobody:x:501:1000:Linux User,,,:/home/nobody:/bin/sh
restsdk:x:0:990:Linux User,,,:/home/restsdk:/bin/sh
messagebus:x:65531:65531:Linux User,,,:/home/messagebus:/bin/sh
media:x:1000:1000:,,,:/usr/share/ftp:/bin/sh
abc:x:1002:1002:Linux User,,,:/home/abc:/bin/sh
```

**Comment by wg-connect2ddentistry** [comment]
it might be something wrong from my side. but do not understand why its happening only with Radarr, except this Sonarr is working 100% fine with PID=0 and PGID=0 (for testing purpose I am using the Root ID 0,0) in case if its running I will switch to other PID and PGID rather than using 0,0

**Comment by j0nnymoe** [comment]
I mean, the logs people are providing are exactly as expected from a working container. No one has said what happens after they've deployed it. 

Also this is best effort attempts to fix as no one with the team has a WD arm Nas unit to test with.

**Comment by wg-connect2ddentistry** [comment]
With my own research and practice, I tried to make a tar of whole container 
`tar -cvf completecontainer.tar /` and `cp /completecontainer.tar /config` 
after extract it I fount the files in `/etc/s6/init/init-stage1`,  `/etc/s6/init/init-stage2`,  `/etc/s6/init/init-stage3`

**Comment by thelamer** [comment]
What in the heck is going on in this issue? Just use the recommended run or compose examples. Github is for bugs and feature requests not support.
