### ISSUE TITLE
nightly: url redirects to ip

### ISSUE THREAD

**Issue by vaneess** [linuxserver/docker-radarr#152]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
radarr can be accessed trough outside like in develop version

## Current Behavior
i everyone 
i'm using the nightly build of radarr. for about 2 weeks, i get redericted to https://ipadress:7878/login?ReturnUrl=%2F and get a SSL error (ERR_SSL_PROTOCOL_ERROR) when i try to access my radarr from outside through https://radarr.domain (i'm using a sophos firewall with virtual webservers for redirecting to https)

the problem does not exist in the develop version with the same settings.
## Steps to Reproduce

1. install latest nigthly version
2. set general settings to: bind address = *, port number = 7878, URL base = *empty*, enable ssl = false
3. configure your firewall so you can access radarr from external over https (virtual webserver)

## Environment
**OS:** ubuntu lts 20.04.3 
**CPU architecture:** x64
**How docker service was installed:**
Version 4.0.0.5497
Package Version 4.0.0.5497-ls155 by linuxserver.io
.NET Yes (5.0.10)
Docker Yes
DB Migration 199

## Command used to create docker container (run/create/compose/screenshot)
docker create \
  --name=radarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Zurich\
  -p 7878:7878 \
  -v /var/docker/radarr/config:/config \
 -v /var/Media/Filme:/movies \
  -v /var/docker/sabnzbd/datadir/Downloads:/Downloads \
  --restart unless-stopped \
  linuxserver/radarr:nightly

**Comment by Roxedus** [comment]
This is not a container issue. It also sounds like this upstream issue https://github.com/Radarr/Radarr/issues/6676
