### ISSUE TITLE
Movie images from a previously corrupt db survive nuke

### ISSUE THREAD

**Issue by arette** [linuxserver/docker-radarr#16]
I believe there is a bug in Radarr's bulk import that somehow allowed me to screw up the db.  Fine, so I blew everything in /config away, furthermore even deleted the container and its image and re downloaded from scratch.  I also confirmed that, at that point, no references to radarr anywhere on the filesystem of my synology.

However, when I get redownload the image, setup and launch the container, there still magically seem to be remnants of the old corrupt db but this is impossible (see below).  Blade Runner 2049 is a movie I had in the db before corruption, but the image is now reappearing as LEGO Ninjango even though I've not readded to the database.  The only thing that appears incorrect is the "cover" image.  I noticed similar behavior on Lidarr (https://github.com/lidarr/Lidarr/issues/169) so makes me wonder how the underlying web ui is managing this "cover" image (eg are they cached outside the database itself), how could something like this survive a complete uninstall, "rm -rf" db nuke?  The behavior also continues as I continue to add movies, old incorrect cover images continue to appear on these newly added movies.  Although I'm kinda curious if it would ever "come out of it", I thought it better to reach out to the experts.

I'm opening this issue here and on Radarr's page because it is unclear to me at this point given my one data point whether this is a (latent) issue with the docker "ports" or whether it is inside Radarr itself.  Either way, I'd expect to be able to start from scratch.

![2018-01-01 01_49_57-movies - radarr](https://user-images.githubusercontent.com/12751515/34466076-18548248-ee96-11e7-96cd-83ef63fc1882.png)

![2018-01-01 01_54_45-the lego ninjago movie - radarr](https://user-images.githubusercontent.com/12751515/34466098-c74fa8b8-ee96-11e7-9183-46abb8b0f18b.png)

![2018-01-01 02_04_06-movies - radarr](https://user-images.githubusercontent.com/12751515/34466135-116a4cea-ee98-11e7-8042-38a41bd6e768.png)

![2018-01-01 02_04_32-the foreigner - radarr](https://user-images.githubusercontent.com/12751515/34466138-26ce49b0-ee98-11e7-8a7e-e15a869cf0aa.png)

**Comment by tobbenb** [comment]
Have you tried clearing your browser cache?

**Comment by arette** [comment]
Did the trick lol!
