### ISSUE TITLE
Remove mediainfo from develop branch

### ISSUE THREAD

**Issue by daverof** [linuxserver/docker-radarr#160]
As `develop` [was updated to](https://www.reddit.com/r/radarr/comments/rvb52f/new_release_radarr_v4005745_develop/) `nightly` a few days back, you can now remove [mediainfo](https://github.com/linuxserver/docker-radarr/blob/develop/Dockerfile) in `develop` as you did for `nightly` [here](https://github.com/linuxserver/docker-radarr/commit/8bd305244b8351c396fb0b6a8f062ac818802480)

**Comment by Roxedus** [comment]
Done with the rebase to alpine
