### ISSUE TITLE
Allow dismissal of "This image is now based on Alpine" health message on radarr:nightly

### ISSUE THREAD

**Issue by markmonroy** [linuxserver/docker-radarr#168]
## Desired Behavior
Need to be able to dismiss/ignore this message on Radarr's status page. I'm not using any scripts, so it is irrelevant to me.

## Current Behavior
The below message appears on the Status page, and results in a "1" badge in the sidebar that I can't dismiss.

`This image is now based on Alpine. Custom scripts using apt-get will need to be updated to use apk`

## Alternatives Considered
Tried to ignore it, but it really does annoy me to have a notification that I can't dismiss or take any action on.

**Comment by Roxedus** [comment]
It is not our decision to not allow dismissal of these types of messages. It will be removed in a few days from the image,

**Comment by iammanbeard** [comment]
> It is not our decision to not allow dismissal of these types of messages. It will be removed in a few days from the image,

Who's decision is it to remove it then? I checked the Radarr Discord and the devs say it's the LinuxServer team. It's frustrating that this was added with no other information, especially when it's a health status that gets posted to any external services you're sending health notifications to.

**Comment by despecial** [comment]
Mid of june and still getting this message. When will you remove this?

**Comment by Roxedus** [comment]
> Mid of june and still getting this message. When will you remove this?

we did, 3 months ago. https://github.com/linuxserver/docker-radarr/commit/7827015358f4b6d30b6a7c561de579b60b6edb17

**Comment by despecial** [comment]
@Roxedus thanks. That's weird. I am on Package Version 4.1.0.6175-ls143 by [linuxserver.io](https://linuxserver.io/) and got this message since a couple of days.

**Comment by Roxedus** [comment]
> @Roxedus thanks. That's weird. I am on Package Version 4.1.0.6175-ls143 by [linuxserver.io](https://linuxserver.io/) and got this message since a couple of days.

Its not wierd, because it got added to master 11 days ago, as thats when the trasition happened there

**Comment by despecial** [comment]
I see and will wait until you removed it again from the master. Thanks for clearing up @Roxedus

**Comment by ChrisBaker97** [comment]
In case anyone can't wait, removing the last line (`PackageGlobalMessage=Warn: This image is now based on Alpine. Custom scripts using apt-get will need to be updated to use apk`) from `/app/radarr/package_info` inside the running container (`docker exec -it radarr /bin/bash`) and restarting will clear the message until the next time the container is updated.

**Comment by ChrisBaker97** [comment]
Would it be acceptable to modify the `Dockerfile` so that the warning message is only appended if `apt-get` is `grep`'d in a file inside the `/config/custom-cont-init.d` directory? Seems like that would limit showing the warning message only to users who might be affected.
