### ISSUE TITLE
After update Radarr doesn't want to start and seems to want to recreate database (and fails)

### ISSUE THREAD

**Issue by djmulder** [linuxserver/docker-radarr#169]
Hey there,

Yesterday I updated radarr to the latest and now it doesn't want to start up anymore. upon reviewing logs it seems it tries to recreate the database. 

https://pastebin.com/8etFy4bs

Is there a way to fix this? I considered just having it create a new database and just import existing data to it, but my sqlite is rusty so I don't know the proper course of action.

**Comment by Roxedus** [comment]
Please follow the issue template.

**Comment by djmulder** [comment]
Done, see new issue :)
