### ISSUE TITLE
Login form in combination nginx

### ISSUE THREAD

**Issue by To0wnn** [linuxserver/docker-radarr#174]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Should not redirect to local ip
## Current Behavior

Redirect to local ip
## Steps to Reproduce

1. Activate Login form
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
 latest

## Command used to create docker container (run/create/compose/screenshot)

docker run -d \
--name=radarr \
-p 7878:7878 \
-e PUID=1000 \
-e PGID=1000 \
-e UMASK=002 \
-e TZ=Europe/Amsterdam \
-e ARGS="" \
-v /mnt/pool-0/docker/radarr:/config \
-v /mnt/pool-0/certs:/certs:ro \
-v /mnt/pool-0/downloads:/downloads \
-v /mnt/pool-1/movies:/movies \
-v /mnt/pool-1/tv-shows:/tv-shows \
--restart unless-stopped \
lscr.io/linuxserver/radarr:latest

## Docker logs

[radarr.zip](https://github.com/linuxserver/docker-radarr/files/8883433/radarr.zip)

**Comment by Roxedus** [comment]
This sounds like a issue with your reverse proxy. It's definitely not a issue with the container.

**Comment by To0wnn** [comment]
Same settings as sonarr and bazarr and not having this issue

**Comment by To0wnn** [comment]
Using swag docker now. It is working now.. Strange.. Thanks anyway!
