### ISSUE TITLE
4.1.0.6175 - No UI available on port, no error messages being recorded

### ISSUE THREAD

**Issue by acurrington** [linuxserver/docker-radarr#180]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Should be able to access the web UI

## Current Behavior
Get a message saying "This site can't be reached"

## Steps to Reproduce
After upgrading to 4.1.0.6175...
Start Docker container for Radarr
Wait for log to show Radarr container started
Try to access port 7878
Nothing appears to be listening, even though image still appears to be running ok.
No changes to anything Docker or IP related other than pulling the new image. Before this version, the UI showed without an issue.

## Environment
"Latest" Image was pulled from Linuxserver.io

## Command used to create docker container (run/create/compose/screenshot)
Pulled within PortainerCE

## Docker logs
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun radarr (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.1.0.6175 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:7878 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/radarr/bin

**Comment by Roxedus** [comment]
Post the configuration you set in portainer

**Comment by acurrington** [comment]
image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /path/to/my/data:/config
      - /path/to/my/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

**Comment by acurrington** [comment]
After removing the docker container, renaming the persistent config directory, and re-deploying the container, I now see the following

[Info] FluentMigrator.Runner.MigrationRunner: 192: add_on_delete_to_notifications migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0587345s 
[Info] FluentMigrator.Runner.MigrationRunner: 194: add_bypass_to_delay_profile migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] add_bypass_to_delay_profile: Starting migration of Log DB to 194 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (194, '2022-07-12T09:29:02', 'add_bypass_to_delay_profile') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 194: add_bypass_to_delay_profile migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.112132s 
[Info] FluentMigrator.Runner.MigrationRunner: 195: update_notifiarr migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] update_notifiarr: Starting migration of Log DB to 195 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (195, '2022-07-12T09:29:02', 'update_notifiarr') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 195: update_notifiarr migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0209055s 
[Info] FluentMigrator.Runner.MigrationRunner: 196: legacy_mediainfo_hdr migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] legacy_mediainfo_hdr: Starting migration of Log DB to 196 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (196, '2022-07-12T09:29:02', 'legacy_mediainfo_hdr') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 196: legacy_mediainfo_hdr migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0309748s 
[Info] FluentMigrator.Runner.MigrationRunner: 197: rename_blacklist_to_blocklist migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] rename_blacklist_to_blocklist: Starting migration of Log DB to 197 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (197, '2022-07-12T09:29:02', 'rename_blacklist_to_blocklist') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 197: rename_blacklist_to_blocklist migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0670738s 
[Info] FluentMigrator.Runner.MigrationRunner: 198: add_indexer_tags migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] add_indexer_tags: Starting migration of Log DB to 198 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (198, '2022-07-12T09:29:02', 'add_indexer_tags') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 198: add_indexer_tags migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0657246s 
[Info] FluentMigrator.Runner.MigrationRunner: 199: mediainfo_to_ffmpeg migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] mediainfo_to_ffmpeg: Starting migration of Log DB to 199 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (199, '2022-07-12T09:29:02', 'mediainfo_to_ffmpeg') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 199: mediainfo_to_ffmpeg migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0657679s 
[Info] FluentMigrator.Runner.MigrationRunner: 200: cdh_per_downloadclient migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] cdh_per_downloadclient: Starting migration of Log DB to 200 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (200, '2022-07-12T09:29:02', 'cdh_per_downloadclient') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 200: cdh_per_downloadclient migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.1101048s 
[Info] FluentMigrator.Runner.MigrationRunner: 201: migrate_discord_from_slack migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] migrate_discord_from_slack: Starting migration of Log DB to 201 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (201, '2022-07-12T09:29:02', 'migrate_discord_from_slack') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 201: migrate_discord_from_slack migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0269028s 
[Info] FluentMigrator.Runner.MigrationRunner: 202: remove_predb migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] remove_predb: Starting migration of Log DB to 202 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (202, '2022-07-12T09:29:02', 'remove_predb') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 202: remove_predb migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0591173s 
[Info] FluentMigrator.Runner.MigrationRunner: 203: add_on_update_to_notifications migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] add_on_update_to_notifications: Starting migration of Log DB to 203 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (203, '2022-07-12T09:29:02', 'add_on_update_to_notifications') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 203: add_on_update_to_notifications migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0287404s 
[Info] FluentMigrator.Runner.MigrationRunner: 204: ensure_identity_on_id_columns migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] ensure_identity_on_id_columns: Starting migration of Log DB to 204 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (204, '2022-07-12T09:29:02', 'ensure_identity_on_id_columns') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 204: ensure_identity_on_id_columns migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0324916s 
[Info] FluentMigrator.Runner.MigrationRunner: 205: download_client_per_indexer migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] download_client_per_indexer: Starting migration of Log DB to 205 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (205, '2022-07-12T09:29:02', 'download_client_per_indexer') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 205: download_client_per_indexer migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0658128s 
[Info] FluentMigrator.Runner.MigrationRunner: 206: multiple_ratings_support migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] multiple_ratings_support: Starting migration of Log DB to 206 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: INSERT INTO "VersionInfo" ("Version", "AppliedOn", "Description") VALUES (206, '2022-07-12T09:29:03', 'multiple_ratings_support') 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Committing Transaction 
[Info] FluentMigrator.Runner.MigrationRunner: 206: multiple_ratings_support migrated 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0665604s 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:7878 
[Info] UpdaterConfigProvider: Update mechanism BuiltIn not supported in the current configuration, changing to Docker. 
[Info] ProfileService: Setting up default quality profiles 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/radarr/bin 

However, I still can't connect to port 7878

**Comment by myna-me** [comment]
Smiliar issues here. There are no error messages, but there is no UI available. 
Tried the same Docker commands.
Not sure if this is the same as OP, but this occurs in a synology box.
I tried it in another box and LATEST, or version 4.1.0 work fine.
However in this box it does not. But if i run version 4.0.5, then it runs with no problems.
A couple of other things i tried:
- deleted everything and started from scratch
- passed UID and GID of an admin user
- passed UID and GID of root user

in all instances, the /config directory correctly gets the owner/group setup, but 2 directories get created inside: custom-cont-init.d and custom-services.d, both under ROOT user. The container stays running, but i get no GUI. just "The connection was reset" msg.
Other than that, here is the log:

```
[custom-init] no custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1029
User gid:    65540
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun radarr (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
```

**Comment by myna-me** [comment]
@emberduck , Interestingly enough I am also on a DS1512+, with the latest DSM6.2.4U6.
I have tried starting from scratch, starting from portainer, starting from Synology's wizzard and my usual, starting from ansible. Same situation. but no problems with version 4.0.5
At some point i had it running on a different docker server in a ubuntu box, with the storage mounted as NFS. However Radarr is very chatty and having the DB on the network was causing a lot of issues on the DB, so i decided to move to the synology where it would be local.

Could anyone give @emberduck and me some ideas on where else to look?
Thank you!

**Comment by j0nnymoe** [comment]
@emberduck if you could actually provide some logs and your docker compose you're using to deploy the container, that would be helpful.
@myna-me please could you provide your compose?

**Comment by myna-me** [comment]
Thanks for assisting, @j0nnymoe 

Here is the docker run command:
  docker run -d  \
    -v /volume2/docker/radarr:/config \
    -v /volume2/media/downloads/radarr:/downloads \
    -v /volume2/media/movies:/movies \
    -e TZ=America/New_York \
    -e PUID=0 \
    -e PGID=0 \
    -p 7878:7878 \
    --name "radarr" \
    --restart=unless-stopped \
    linuxserver/radarr:latest 

Here are a couple more things i've done, which may give you some idea:

- Erased everything and created the target directory again, making sure the ownership was root:root (again, just trying everything at this point)
- run the command above, which resulted in the same helpful-less log. lol.
- Went ahead and opened up a shell into the container ( `docker exec -it radarr /bin/sh` ) and did a `ls -al /`
- at that point, i noticed that though everything was owned by root, the config directory had NO permissions set.
- within that shell, i set permissions to full access (`chmod -R 777 config`), got out and restarted the container
- went back in, permissions were still in place....but no files in it, no response

something else i noticed while in the shell. DMESG showed several time the following error, which may give you another hint:
`[36284567.908211] Radarr[5099]: segfault at 20 ip 00007fd2313a7714 sp 00007ffd9ed1c320 error 6 in libclrjit.so[7fd23137d000+26e000]`

Google-fu showed other people having segfault errors in the past with their NAS devices, but those were arm processors. ours is Intel x86.

As usual, i tried all of the above with v4.0.5 and it is not a problem.

I am attaching the portainer log, showing the initial run, stopping of container, and restart.
[_radarr_logs.txt](https://github.com/linuxserver/docker-radarr/files/9992790/_radarr_logs.txt)

**Comment by myna-me** [comment]
Ok. Last night, through a lot of google, i found a post that mentioned that the newer versions of alpine don't work well with our CPUs (cedarview on the 1512+ in my case). Though the explanation was not satisfactory because i have other linuxserver containers running just fine, I finally took the plunge and migrated everything to use the PostgreSQL DB, so that i can run this container in another server. (this solves the issue of the sqlite db corruption, when storing container files in the synology but running the container on another server).
The documentation in the radarr site ([HERE](https://wiki.servarr.com/radarr/postgres-setup)) has a couple of issues, but I was definitely able to do it.
The main thing to remember, is to NOT restore from a backup. so here are the steps i followed (at a high level):

- Use the latest image for the container, as is....which won't work as stated above. however, it does the data schema updates in the sqlite db.
- Turn off. Follow the steps in the link above for setting up the postgres backend, and start the container. it should be blank.
- Stop it again and follow the steps to do the data load....however, the syntax there was not working so here was my work around (after following all the steps prior to the data load command":
  - create a file called db.load in the same directory where the radarr.db file is.
  - add the following text:
`load database`
`    from /radarr.db`
`    into pgsql://qstick:qstick@dbserver/radarr-main`
`  with prefetch rows = 100, batch size = 1MB, data only, quote identifiers`
`;`
replacing the user/pw info as needed, and dbserver, for the server name of the **docker** host running the postgres container
  -   on the docker host where you will run radarr (NOT on the synology), issue this command:
  `sudo docker run --rm --name pgloader -v /path/to/containers/radarr/radarr.db:/radarr.db -v /path/to/containers/radarr/db.load:/db.load --network=host ghcr.io/roxedus/pgloader /db.load`
  - and voila. 

It runs much better and snappier, it freed up cpu and mem resources on the synology and hey, we can now run on the latest version.

I hope this helps someone.

**Comment by theonlyway** [comment]
I don't know if my issue is related to this or not but chances are it is given I'm using a Synology as well. It's a pretty old Snyology Nas a DS412+ with an Intel Atom D2700. The issue appears to be something to do with either Alpine or the musl variant of Radarr. If I make change the dockerfile to use Ubuntu instead of Alpine everything works.

```docker
# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-ubuntu:jammy

# set version label
ARG BUILD_DATE
ARG VERSION
ARG RADARR_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

# environment settings
ARG RADARR_BRANCH="master"
ENV XDG_CONFIG_HOME="/config/xdg"

RUN \
  echo "**** install packages ****" && \
  apt-get update && apt-get install -y \
  curl \
  jq \
  libicu-dev \
  sqlite3 && \
  echo "**** install radarr ****" && \
  mkdir -p /app/radarr/bin && \
  if [ -z ${RADARR_RELEASE+x} ]; then \
  RADARR_RELEASE=$(curl -sL "https://radarr.servarr.com/v1/update/${RADARR_BRANCH}/changes?os=linux&runtime=netcore" \
  | jq -r '.[0].version'); \
  fi && \
  curl -o \
  /tmp/radarr.tar.gz -L \
  "https://radarr.servarr.com/v1/update/${RADARR_BRANCH}/updatefile?version=${RADARR_RELEASE}&os=linux&runtime=netcore&arch=x64" && \
  tar xzf \
  /tmp/radarr.tar.gz -C \
  /app/radarr/bin --strip-components=1 && \
  echo -e "UpdateMethod=docker\nBranch=${RADARR_BRANCH}\nPackageVersion=${VERSION}\nPackageAuthor=[linuxserver.io](https://linuxserver.io)" > /app/radarr/package_info && \
  echo "**** cleanup ****" && \
  rm -rf \
  /app/radarr/bin/Radarr.Update \
  /tmp/*

# copy local files
COPY root/ /

# ports and volumes
EXPOSE 7878

VOLUME /config
```
