### ISSUE TITLE
/etc/services.d/radarr/run is no longer marked as executable, breaking s6 read-only root

### ISSUE THREAD

**Issue by Avamander** [linuxserver/docker-radarr#181]
*Note: Quite a few linuxserver containers broke like this relatively recently*

## Expected Behavior
The file "/root/etc/services.d/radarr/run" is no longer marked executable in the container, configurations utilizing S6_READ_ONLY_ROOT and what mark the root read-only will fail. This is a regression compared to the previous builds.

## Current Behavior
The `./run` file of the radarr service is `rw-rw-r--` instead of `rwxrw-r--` causing the following error message:
```
radarr     | s6-supervise radarr (child): fatal: unable to exec run: Permission denied
radarr     | s6-supervise radarr: warning: unable to spawn ./run - waiting 10 seconds
```
One `chmod` in the container fixes that.

## Steps to Reproduce
Add the snippet provided below to your compose file.

## Similar symptoms or issues: 
* https://github.com/kubeflow/kubeflow/issues/5808#issuecomment-1083558197
* https://github.com/rocker-org/rocker/issues/202
* https://github.com/containers/podman/issues/3803
* https://github.com/Radarr/Radarr/issues/5300
* https://github.com/linuxserver/docker-radarr/issues/113
* https://github.com/just-containers/s6-overlay/issues/158
* https://github.com/linuxserver/docker-homeassistant/issues/54

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** arm64
**How docker service was installed:** Official repos

## Command used to create docker container
```
    read_only: true
    tmpfs:
      - /run:rw,exec
      - /tmp:rw,noexec,nosuid
    environment:
      - "S6_READ_ONLY_ROOT=1"
```

**Comment by fexofenadine** [comment]
I've been getting a similar issue with every build (latest, develop or nightly) subsequent to linuxserver/radarr:4.1.0.6175-ls151 . the GUI never loads up after the run script fails:

the errors that show up are:
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service custom-svc-README.txt: starting
s6-supervise custom-svc-README.txt (child): fatal: unable to exec run: Exec format error
s6-supervise custom-svc-README.txt: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise custom-svc-README.txt (child): fatal: unable to exec run: Exec format error
s6-supervise custom-svc-README.txt: warning: unable to spawn ./run - waiting 10 seconds

the last two warnings will repeat indefinitely. rolling back to 4.1.0.6175-ls151 immediately resolves the issue

**Comment by Avamander** [comment]
@fexofenadine Run `docker exec radarr chmod 744 /var/run/s6/services/radarr/run` after you create the container and it'll fix the container with the broken image. Not the prettiest though.

**Comment by j0nnymoe** [comment]
@fexofenadine this isn't the same issue - you need to delete the readme.txt file in your custom folders in the `/config` mount.

**Comment by fexofenadine** [comment]
thanks mate that's got it sorted

**Comment by Avamander** [comment]
Unstale.
