### ISSUE TITLE
Radarr Decided to Delete EVERY.SINGLE.MOVIE

### ISSUE THREAD

**Issue by gettingerr** [linuxserver/docker-radarr#182]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Radarr does not delete all my movie files.

## Current Behavior

Radarr deleted all my movie files

## Steps to Reproduce

1. Have Radarr installed
2. Radarr deletes all my movie files
3. I am sad

## Environment
**OS:** Unraid 6.10.3
**CPU architecture:** x86_64 (AMD Ryzen 5 2600)
**How docker service was installed:** Using Unraid App Store

## Docker logs

Here are my radarr logs showing the mass deletion of files. Can anyone tell me why this happened?
[radarr.3.txt](https://github.com/linuxserver/docker-radarr/files/9264918/radarr.3.txt)
[radarr.2.txt](https://github.com/linuxserver/docker-radarr/files/9264919/radarr.2.txt)

Starts at 2022-08-04 12:48:50.2 on log 3 and continues into log 2.'

Note "Clean Library Level" in Lists is set to "Disabled"

Edit: Yes I am a buffoon and didn't ever set up a Recycle Bin folder. So go me and RIP to my internet provider for the 8TB of movies I am about to redownload...

**Comment by Roxedus** [comment]
Radarr don't remove items without being told. If you expose this to the internet unsecured, someone might just have found your instance. 

Regardless this has nothing to do with the container.

**Comment by gettingerr** [comment]
> Radarr don't remove items without being told. If you expose this to the internet unsecured, someone might just have found your instance.
> 
> Regardless this has nothing to do with the container.

Got it. People are big meanies and I need to be a little more careful. Lessons learned, hope my ISP doesn't mind the data hit this week. 

Thanks for the info!
