### ISSUE TITLE
When to move from nightly to master

### ISSUE THREAD

**Issue by bigdant** [linuxserver/docker-radarr#187]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

**Comment by bigdant** [comment]
Hi,

I’d like to move my instances from nightly to master/ stable.

I know this is a rarely available option and only when the nightly and master versions are in sync. Is there anyway to know when this would happen.

rhe only reason I’m on nightly is because a long time ago this was the only way to
Get v3 of radarr.  Now it’s been release I’d like to be able to get off nightly and onto master.

cheers

D

**Comment by aptalca** [comment]
That's really a question for radarr. You can probably ask in their discord channel and their devs may chime in.

**Comment by Roxedus** [comment]
https://wiki.servarr.com/radarr/faq#how-do-i-update-radarr
