### ISSUE TITLE
radarr and nzbget integration

### ISSUE THREAD

**Issue by estimadarocha** [linuxserver/docker-radarr#2]
i use linuxserver dockers in container station of my qnap... all of them working good.

radarr also works good if working alone but if i choose to add the shares from the nzbget docker also from linuxserver radarr doesn't start and keep saying... press enter to exit

**Comment by j0nnymoe** [comment]
@estimadarocha Please could you post some more information about your setup, mainly the settings for the containers in question (mount points/networking info etc). We will help as much as we can but no one in the team has access to any qnap hardware so testing will be an issue.

**Comment by estimadarocha** [comment]
@j0nnymoe see the pictures qith the options:

http://prnt.sc/e6j77f
http://prnt.sc/e6j7ic
http://prnt.sc/e6j7yk

**Comment by j0nnymoe** [comment]
@estimadarocha I think you need to try and setup this docker without using the shares from the NZBget data and just make sure that the -v mount points are mounted to the same locations as nzbget. This should get around your issue.

**Comment by sparklyballs** [comment]
no reply from user on potential fix.

closing.

**Comment by estimadarocha** [comment]
just to give a word about this i tried the solution porposed by @j0nnymoe but without sucess using just the mount points and even they point to same place i am not able to acess content from the other docker... maybe a qnap issue
