### ISSUE TITLE
[BUG] Connection refused (api.radarr.video:443)

### ISSUE THREAD

**Issue by SBerg1980** [linuxserver/docker-radarr#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot search new movies, i see this event: System.Net.Http.HttpRequestException: Connection refused (api.radarr.video:443): Connection refused (api.radarr.video:443)

### Expected Behavior

Find the movie

### Steps To Reproduce

Search Radarr

### Environment

```markdown
- OS: Docker
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    networks:
      default:
        ipv4_address: 10.0.0.45
    volumes:
      - /NAS/CON/radarr:/config
      - /NAS/MUL/MOV:/media #optional
      - /NAS/DOW/MOV:/downloads #optional
    restart: unless-stopped
networks:
  default:
    external:
      name: macvlan-br0
```

### Container logs

```bash
[Fatal] ConsoleApp: Failed to bind to address http://[::]:7878: address already in use. This can happen if another instance of Radarr is already running another application is using the same port (default: 7878) or the user has insufficient permissions 
Press enter to exit...
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.3.2.6857 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] SingleInstancePolicy: 1 instance(s) of Radarr are running 
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
```

**Comment by j0nnymoe** [comment]
It's going to be a networking issue due to the network info you've put into your docker-compose file.

**Comment by parsec** [comment]
> I have found the problem it was Ad Blocking on Unifi Firewall.

i just had this same problem. thanks for coming back and documenting your finding, it helped a fellow confused soul today!

**Comment by Mi3liX9** [comment]
I have same problem but I don't have any VPN or adblock

**Comment by j0nnymoe** [comment]
As mentioned, it's going to be an issue related to your network, not the container.

**Comment by gorillaink** [comment]
same issue with Ad Blocking on Unifi firewall, thanks @SBerg1980 , would never have found that out on my own !

**Comment by itzteajay-glitch** [comment]
Solid find it was unifi ad-block for me too!

**Comment by tpaz900** [comment]
> I have found the problem it was Ad Blocking on Unifi Firewall.

Amazing! Had the exact same issue. However, the Sonarr was working fine with Ad Blocking enabled on UDM. How weird is that...
Disabled and it works now. Thanks a million!

**Comment by AidanMalchor** [comment]
Nice find, would never have thought about the ad-block in unifi.

**Comment by jadehawk** [comment]
Thank you!! Unifi AdBlock was the issue.
