### ISSUE TITLE
[BUG] Latest update causes blank screen

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-radarr#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Blank browser screen on `4.3.2.6857-ls167` . Console shows:

`index.js?h=lMESq5YDg9C43iacfjpbsA:1 Uncaught SyntaxError: Invalid or unexpected token (at index.js?h=lMESq5YDg9C43iacfjpbsA:1:385273)`

Radarr (Docker) log shows:

```
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.3.2.6857
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] CommandExecutor: Starting 2 threads for tasks.
[ls.io-init] done.
```

When I run [4.3.2.6857-ls166](https://hub.docker.com/layers/linuxserver/radarr/4.3.2.6857-ls166/images/sha256-5193c83bb12a46b6aaf87701656df510edff48a0905ea9173f19a8de37c06f65?context=explore) it works fine.

### Steps To Reproduce

Not sure. Run Radarr with a DB from the previous version I guess?

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
radarr:
    image: lscr.io/linuxserver/radarr
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
    volumes:
      - /opt/dockers/mediabox/radarr/config:/config
      - /media/movies:/movies
      - /download:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
```

### Container logs

```bash
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.3.2.6857
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] CommandExecutor: Starting 2 threads for tasks.
[ls.io-init] done.
```

**Comment by thespad** [comment]
These are the only changes between those releases: https://github.com/linuxserver/docker-radarr/compare/4.3.2.6857-ls166...4.3.2.6857-ls167, a few minor OS package updates. I've spun up a test container using 4.3.2.6857-ls167 and it works fine:


![Image](https://user-images.githubusercontent.com/8425502/232096557-f907f472-a2b2-4862-bfbb-cfaf6de88b97.png)


Please test 4.3.2.6857-ls167 with a clean /config mount and see if you can replicate the issue.
