### ISSUE TITLE
[BUG] Remote path doesn't seem to be taken into consideration

### ISSUE THREAD

**Issue by Guesch** [linuxserver/docker-radarr#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a permission error (13) in Transmission when the download is completed.

### Expected Behavior

Here is my setup:
Directory is: /mnt/user/download/completed
Transmission has this mapping: /data/completed = /mnt/user/download/completed
Radarr (& Sonarr) have this mapping: /downloads = /mnt/user/download/completed

In **both** Radarr & Sonarr, I have this configuration for the remote pathing:
remote path = /data/completed/
local path = /downloads

When comparing in Transmission what is the file location when a torrent start, I have:
From Sonarr: /data/completed (Correct)
From Radarr: /downloads (Incorrect)

Sonarr is working as expected (able to move files after the download is completed), I would expect Radarr to do the same.

### Steps To Reproduce

See above

![image](https://github.com/linuxserver/docker-radarr/assets/61683661/6e24d1b4-55ca-4f56-9024-60d218034bdf)

### Environment

```markdown
- OS: Unraid
- How docker service was installed: Unraid app store
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='radarr'
  --net='bridge'
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="XXXX"
  -e HOST_CONTAINERNAME="radarr"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:7878]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-logo.png'
  -p '7878:7878/tcp'
  -v '/mnt/user/Movies/':'/movies':'rw'
  -v '/mnt/user/download/completed/':'/downloads':'rw'
  -v '/mnt/user/appdata/radarr':'/config':'rw' 'lscr.io/linuxserver/radarr'
ef84183cc96e9147db9da7a21fd7f5493550d27f0a411fa3700b4e8fbebca824
```

### Container logs

```bash
n/a
```

**Comment by Roxedus** [comment]
This is a application support request, not a container issue.
