### ISSUE TITLE
armv7 support for docker image

### ISSUE THREAD

**Issue by khalith** [linuxserver/docker-radarr#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been running armv7 architecture of docker in my raspberry pi and currently latest version of radarr is missing for this architecture. Can any one help me to get the same?

### Steps To Reproduce

Use docker tag with --platform linux/armv7

### Environment

```markdown
- OS: raspberry pi OS
- How docker service was installed: docker compose
```

### CPU architecture

arm64

### Docker creation

```bash
radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Asia/Kolkata"
    volumes:
      - /home/pi/Radarr/config:/config
      - /media/pi/Plex/Movies:/movies
      - /media/pi/DOWNLOADS/Downloads:/downloads
      - /media/pi/DOWNLOADS/Movies-Deleted:/Movies-Deleted
    ports:
      - 7878:7878
    restart: unless-stopped
```

### Container logs

```bash
None
```

**Comment by Roxedus** [comment]
We do no longer support armhf. https://www.linuxserver.io/blog/a-farewell-to-arm-hf
