### ISSUE TITLE
[BUG] RROR: no matching manifest for linux/arm/v7 in the manifest list entries on raspberrypi

### ISSUE THREAD

**Issue by maryum375** [linuxserver/docker-radarr#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems like the latest version of `linuxserver/radarr:arm32v7-latest` (sha256:431e681b516818d737852e9200e22915e885fc12258de318420a82d8cd636a17) is built over `linux/amd64` which makes it break when pulling on a raspberrypi:
`ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

Same for sonarr btw

### Expected Behavior

Build it on top if `linux/arm/v7`

### Steps To Reproduce

Set the image to `linuxserver/radarr:arm32v7-latest` on a raspberrypi
pull the image

### Environment

```markdown
- OS: raspbian
- CPU arm32 (ignore the below CPU)
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up -d

    radarr:
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Jerusalem
            - UMASK=022
        ports:
            - '7878:7878'
        restart: unless-stopped
        image: linuxserver/radarr:arm32v7-latest
```

### Container logs

```bash
no logs as image pulling fails
```

**Comment by j0nnymoe** [comment]
We no longer build armhf containers - https://info.linuxserver.io/issues/2023-07-01-armhf/

**Comment by maryum375** [comment]
I am running on a raspberrypi 4 model B revision: c03111
```
uname -m
armv7l
```
Do you know if I can install a 64bit os on that processor?

**Comment by aptalca** [comment]
`latest` tag won't work for you. A specific version/build tag will work, but we highly recommend against them as they are very old at this point.

To build them, you would have to start with the baseimage and build that locally with 32bit support, and then build the downstream image based on that new local image. It's an option for advanced users.
