### ISSUE TITLE
 [BUG] Connection refused (api.radarr.video:443) #204 

### ISSUE THREAD

**Issue by madereddy** [linuxserver/docker-radarr#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[v5.0.1.7993] System.Net.Http.HttpRequestException: Connection refused (api.radarr.video:443)

### Expected Behavior

Tried to comment on issue: https://github.com/linuxserver/docker-radarr/issues/204 but its been marked closed. Found the resolution to the issue.

Create a new rule in traffic management to allow radarr to connect to the api.

Action: Allow
Category: Domain Name
Domain Name:
+Add: [api.radarr.video](https://api.radarr.video/)
Target: (select the radarr server)
Schedule: Always

### Steps To Reproduce

Add from Ombi to Radarr

### Environment

```markdown
- OS: Synology DSM 7
- How docker service was installed: Synology Container Manager
```

### CPU architecture

x86-64

### Docker creation

```bash
Default run mounting drives and opening port 7878
```

### Container logs

```bash
[v5.0.1.7993] System.Net.Http.HttpRequestException: Connection refused (api.radarr.video:443)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.attemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Radarr.Common/Http/Dispatchers
```

**Comment by j0nnymoe** [comment]
This "issue" isn't anything to do with the container and as documented in the previous issue that its outside factors that users have in place causing the problem.

**Comment by madereddy** [comment]
@j0nnymoe I just wanted to be able to update the previous ticket with the solution. Would you be able to update it in ticket for other users run across the same issue? Im fine with this ticket being closed.

**Comment by j0nnymoe** [comment]
Personally, I would expect to see something like this in an faq of radarr itself because you'd experience this same issue regardless of it being in a container or not. I would see if they have an faq you can submit it to.

**Comment by Roxedus** [comment]
This is already covered in radarrs documentation.

**Comment by j0nnymoe** [comment]
Even better.

**Comment by vgdh** [comment]
have the same error
https://api.lidarr.audio/api/v0.4/search?type=all&query=ac%20dc
Sorry, you have been blocked
