### ISSUE TITLE
'Press enter to exit' after latest version (92)

### ISSUE THREAD

**Issue by azgul** [linuxserver/docker-radarr#23]
After watchtower updated my radarr containers to version :latest/:92 I get an endless loop of `Press enter to exit`:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.


Press enter to exit...


Press enter to exit...
```

with seemingly no end.

Reverting back to :91 and it works fine again.

**Comment by that1guy** [comment]
Same issue here.  Rolled back and everything is working perfectly.  Latest build is the culprit.

**Comment by glassbase** [comment]
Me too.

**Comment by suivethefirst** [comment]
Same issue, and rolling back to :91 is fine.

**Comment by sparklyballs** [comment]
try exec'ing in to the container and running cd /opt/radarr && curl -o - http://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz | gunzip -c > NLog.dll  and then restarting the container

**Comment by SlothCroissant** [comment]
This fixed it for me. However will this fix be pushed into the docker file itself for new deployments? 

One of the things I tried before finding this thread was recreating the container from scratch (with my volumes mapped,etc), and the issue persisted. 

Thanks for the quick fix!

**Comment by sparklyballs** [comment]
Hope is radarr will fix upstream

**Comment by WolfieNuke** [comment]
Thank you!!! I was about to bash my head in and luckily a quick google search led me to the solution.

I appreciate the workaround!

**Comment by gnarr** [comment]
Thank you sparklyballs! Fixed it for me! 👍
