### ISSUE TITLE
Friday night update has broken the image

### ISSUE THREAD

**Issue by Natteverf** [linuxserver/docker-radarr#24]
Image update on 3-3-18 does not work, logs:

[s6-finish] syncing disks.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donations/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    996,
User gid:    992,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
,
,
Press enter to exit...,
,
,
Press enter to exit...,

Was updated by Watchtower, tried scrapping container and image and redeploying, same issue.

**Comment by sparklyballs** [comment]
see #23
