### ISSUE TITLE
Change download URL to HTTPS

### ISSUE THREAD

**Issue by jozemujo** [linuxserver/docker-radarr#26]
Hi sparklyballs,

Thanks for the nice selection of docker images. I recently switched from Sickbeard to Sonarr and Couchpotato to Radarr.

Call me paranoid, but could you please change

`curl "http://radarr.aeonlucid.com/v1/update/${RADARR_BRANCH}/changes?os=linux"`

to https.

They got a Comodo cert w/ Cloudflare and even support TLS 1.3 :) I've also had a look and checked that the https and http version return the same JSON.

Thanks,
Jože

**Comment by JigSawFr** [comment]
+1 thanks !

**Comment by thelamer** [comment]
Since we migrated to the new build setup this is no longer present on either branch.
