### ISSUE TITLE
Couchpotato not snatching torrents

### ISSUE THREAD

**Issue by JTT-JustTheTip** [linuxserver/docker-radarr#28]
OS - Ubuntu Server LTS 16.04, Docker  18.06.1-ce

Docker compose - 
`Radarr:
    image: linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    environment:
      PUID: '1001'
      PGID: '1001'
      TZ: Europe/London
    network_mode: le_bridge
    restart: always
    volumes:
    - /Docker_Configs/Radarr/Config:/config
    - /media/AlphaMedia/Movies:/movies
    - /media/VMRoot/VMMedia/complete/movies:/downloads/complete/movies
    tty: true
    ports:
    - 7878:7878/tcp`

CP is able to find the torrents but it doesnt automatically add them to transmission, cant work out why not though as when i manually select one of the torrents its found it doesnt have any issues

Thanks!

**Comment by CHBMB** [comment]
Errrr.....

But this is Radarr

**Comment by JTT-JustTheTip** [comment]
What ive successfully done here is forgotten to check which tab I was on, christ im special, sorry about this ahahaha
