### ISSUE TITLE
/signalr/negotiate? http 500 errors radarr and sonarr, doesnt happen on non-docker installs

### ISSUE THREAD

**Issue by meffect** [linuxserver/docker-radarr#3]
In my browsers I'm getting SignalR errors /signalr/negotiate? http 500

it only happens with docker .. if I install directly on os, I dont get the errors. I also experience times when sonarr or radarr just spin and dont do anything, which I dont get with non-docker. Maybe its related?

also only happends when I refresh the page or first landing on page. navigation does not cause errors to bubble to console

Has this come up before? I'm running latest docker engine on ubuntu 16.04.1

**Comment by CHBMB** [comment]
Not that I'm aware of.

**Comment by meffect** [comment]
Was a problem with my nfs mount options, can close ! ty

**Comment by davidbonnici1984** [comment]
![image](https://cloud.githubusercontent.com/assets/905774/26417158/a57f2452-40b8-11e7-8d17-c4712a5fda9b.png)
I'm having the same problem... What was the issue with the NFS mount options @meffect ?

Thanks

David

**Comment by j0nnymoe** [comment]
@davidbonnici1984 more than likely permissions

**Comment by davidbonnici1984** [comment]
Thanks @j0nnymoe Ok thanks, can you guide me on that? In which sense please?

**Comment by j0nnymoe** [comment]
@davidbonnici1984 not really unfortunately, I don't use NFS mounts with my docker containers. I always recommend atleast for the /config mount to be local to the system to avoid permission issues.

**Comment by davidbonnici1984** [comment]
I understand! I have a shared volume on my NAS and putting all container configurations stored there. Thanks for the tip though! :)

David
