### ISSUE TITLE
Radarr crashing 

### ISSUE THREAD

**Issue by JTT-JustTheTip** [linuxserver/docker-radarr#34]
The radarr container will remain on, but will stop doing anything and will stop responding to any commands I give to stop, kill, restart. 

Host: Ubuntu 16.04 LTS, Docker 18.06.1-ce
(All deployed via portainer, here is the compose for radarr)
`Radarr:
    image: linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    environment:
      PUID: '1001'
      PGID: '1001'
      TZ: Europe/London
    network_mode: le_bridge
    #restart: always
    volumes:
    - /Docker_Configs/Radarr/Config:/config
    - /media/AlphaMedia/Movies:/movies
    - /media/VMRoot/VMMedia/complete/movies:/downloads/complete/movies
    tty: true
    ports:
    - 7878:7878/tcp`

The log output is normal, just scanning the disk for new files etc, it does indicate any crash, one thing i noticed is the iowait usage is very high on the system when radarr is on.

**Comment by tobbenb** [comment]
Does it work if you remove tty: true?
I don't see a reason to use it at all. If you need access inside the container, use docker exec.

**Comment by JTT-JustTheTip** [comment]
Seems that removing that option has solved the issue, what would it have been doing to cause the crashes do you think?

Many thanks
