### ISSUE TITLE
Dockerhub builds, missing for radarr, what do they mean?

### ISSUE THREAD

**Issue by meffect** [linuxserver/docker-radarr#4]
I'm still new to docker. Sorry I need education

I notice for sonarr there is https://hub.docker.com/r/linuxserver/sonarr/builds/

but for radarr, there is no builds. https://hub.docker.com/r/linuxserver/radarr/builds/

What is this builds section for?

**Comment by sparklyballs** [comment]
it's a difference between an automated and a manual build that we push to the hub.
