### ISSUE TITLE
Logs, not working?

### ISSUE THREAD

**Issue by meffect** [linuxserver/docker-radarr#5]
Linuxserver.io version:- 26 Build-date:- March-03-2017-23:22:11-UTC

`docker logs -f radarr`

```
┌─[11:52:11]─[!usrv]─[~]
└──> docker logs -f radarr
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1030
User gid:    65540
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

I never see another log entry after that

**Comment by CHBMB** [comment]
That's correct.  Those are the docker container logs, the radarr logs can be viewed via the radarr webui

**Comment by meffect** [comment]
Can someone not retarded open this back up

**Comment by tobbenb** [comment]
No, we are all retarded.

**Comment by meffect** [comment]
i know im retarded

**Comment by CHBMB** [comment]
You calling me retarded?

**Comment by sparklyballs** [comment]
@meffect 

you don't understand the difference between a docker log and the log for the app itself and have the nerve to call someone retarded.

**Comment by meffect** [comment]
I didnt say that

**Comment by sparklyballs** [comment]
"Can someone not retarded open this back up"

liar

**Comment by meffect** [comment]
oh, i was referring to the former part of your comment

**Comment by CHBMB** [comment]
My comment was "That's correct. Those are the docker container logs, the radarr logs can be viewed via the radarr webui"

Which bit of that offended you @meffect

**Comment by lokkju** [comment]
It's docker.  the standard practice for the docker logs command is for it to display the logs of the single or primary application in the docker container.

docker-sonarr displays sonarr logs in the docker logs output; it would be expected that docker-radarr would have the same behavior.

**Comment by sparklyballs** [comment]
sonarr and radarr have the same settings in their respective run commands.
the difference between sonarr output and radar output is specifically down to each app.
