### ISSUE TITLE
Latest being pulled the develop tag

### ISSUE THREAD

**Issue by mrjackyliang** [linuxserver/docker-radarr#56]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

```
sudo docker run \
    -d \
    -v /volume1/docker/radarr:/config \
    -v /volume1/media:/volume1/media \
    -v /volume1/downloads:/volume1/downloads \
    --restart always \
    --net=host \
    --name radarr \
    linuxserver/radarr:latest
```
Why is the latest tag being pulled in the develop tag? The current container is stalling frequently, and makes Radarr unusable. I'm running on Synology NAS with the latest version.

**Comment by aptalca** [comment]
If you're asking why the latest tag is using the develop branch of radarr, that's because develop branch is the default branch of radarr. That's their version of their "stable" releases

**Comment by mrjackyliang** [comment]
Oh, got it. thanks.
