### ISSUE TITLE
Unable to import movies

### ISSUE THREAD

**Issue by rinzes** [linuxserver/docker-radarr#60]
I have just installed the latest build but radarr is unable to see the contents of my folder. I have the volume set as follows:

{
         "host_volume_file" : "/media/Movies",
         "mount_point" : "/movies",
         "type" : "rw"
}

I have setup my PUID and PGID per the instructions...

I don't see any permission problems.

**Comment by j0nnymoe** [comment]
Where to start... 

Host OS? Docker run or Compose info? Is `/media/Movies` a remote mount or local?

**Comment by rinzes** [comment]
Host OS is Synology NAS AMD V6. The files are on the local Synology shared drive folder

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-sonarr/issues/126
