### ISSUE TITLE
Radard shows movie folders as empty by using bulk import

### ISSUE THREAD

**Issue by daniel-afo** [linuxserver/docker-radarr#61]
Hello i have a docker container running with radarr.

Here are some informations about the system and so on:
Host OS: Raspbian GNU/Linux 10 (buster)

I start the Docker Container with the following command:
` docker create \
  --name=radarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -e PGID=1001 -e PUID=1001 \
  -p 7878:7878 \
  -v /etc/radarr:/config \
  -v /mnt/ext-hdd/movies:/movies \
  -v /mnt/ext-hdd/Downloads/complete:/downloads \
  --restart unless-stopped \
  linuxserver/radarr:arm32v7-latest`

I tried it also with another -e Argument: "-e UMASK_SET=022" but no difference.

As you can see in the command line, i map the folder /mnt/ext-hdd/Downloads/complete and /mnt/ext-hdd/nzb.to/movies. 

Here are the rights on the docker host for both:
drwxrwxrwx 1 root root 65536 Jul 29 16:51  movies
drwxrwxrwx 1 root root 40960 Dez 10  2017 complete

The files inside of the folder has the same permissions, user and group.

I can see if i create inside of /movie another folder this folder in radarr, but no files there.

First i thought its a permission Problem, but if i start the bash from the container with user abc like: `docker exec -u abc -it radarr /bin/bash`
then i can see the movies in the movie folder.

Here is the container log Output:
`[Debug] Api: [GET] /api/filesystem?includeFiles=false&path=%2Fmovies%2F: 200.OK (3 ms)
[Debug] RootFolderService: Generating list of unmapped folders
[Debug] RootFolderService: 0 unmapped folders detected.
[Debug] RootFolderService: Generating list of unmapped folders
[Debug] RootFolderService: 0 unmapped folders detected.
[Debug] RootFolderService: Generating list of unmapped folders
[Debug] RootFolderService: 0 unmapped folders detected.
[Debug] Api: [POST] /api/rootfolder: 201.Created (195 ms)
[Debug] Api: [GET] /api/profile: 200.OK (19 ms)
[Debug] RootFolderService: Generating list of unmapped folders
[Debug] RootFolderService: 0 unmapped folders detected.
[Debug] Api: [GET] /api/movies/bulkimport?id=16&folder=%2Fmovies%2F&page=1&per_page=15&sort=sortTitle&direction=NaN: 200.OK (61 ms)`

Has someone a idea how could it be fixed?

**Comment by j0nnymoe** [comment]
Are you BMWfan that has this same issue with couchpotato? https://github.com/linuxserver/docker-couchpotato/issues/47#issuecomment-517208703

**Comment by daniel-afo** [comment]
@j0nnymoe you are Right, sorry i was Opening it with the false account. i closed it and reopend it now with the Right once here: https://github.com/linuxserver/docker-radarr/issues/62
