### ISSUE TITLE
No covers - mediacover permissions

### ISSUE THREAD

**Issue by evlo** [linuxserver/docker-radarr#66]
I have this issue in both radarr and sonarr docker installs

```
sudo docker create \
  --name=radarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Prague \
  -e UMASK_SET=777 `#optional` \
  -p 12007:7878 \
  -v ~/docker/radarr/config:/config \
  -v /mnt/usbHddNtfs/movies:/movies \
  --restart unless-stopped \
  linuxserver/radarr
sudo docker start radarr
```
downloaded files also have no permissions
https://i.imgur.com/Wq78DNv.png

I'm not good with linux, this is what i tried (among other attempts with permissions):

sudo docker stop radarr
sudo chown -R vlada /home/me/docker/radarr/config
sudo chmod -R 777 /home/me/docker/radarr/config
sudo chmod **g+s** /home/me/docker/radarr/config
sudo docker start radarr

**id** for me is indeed gid 1000 pid 1000

What should i do to make this work?

**Comment by sparklyballs** [comment]
your umask should be 000 , not 777

**Comment by j0nnymoe** [comment]
No response. Closing ticket.
