### ISSUE TITLE
API history broken

### ISSUE THREAD

**Issue by cblakely** [linuxserver/docker-radarr#7]
Docker version 1.13.1, build 092cba3 on Ubuntu 16.04
Container version: linuxserver/radarr, latest, 021bc74c5607

Application works fine, except when making API call to history, an error is recieved:

```
curl http://localhost:7878/api/history?api-key=[key removed]
{
  "message": "Object reference not set to an instance of an object",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object\n  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourcePaged>b__35_0 (System.Object options) [0x00017] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\REST\\RestModule.cs:129 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x41817550 + 0x0013b> in <filename unknown>:0 "
}
```

In this case, the history in the web GUI is also empty, but I would not expect an error condition for this, instead an empty response, or "no content" 204 status.

**Comment by cblakely** [comment]
Additional testing, even with items in the GUI history, I receive the same error message.

**Comment by sparklyballs** [comment]
i've tried this with the nightly build docker of radarr and receive the same error as you're reporting here

i'd suggest raisIng an issue on [radarr's git repository](https://github.com/Radarr/Radarr) about this.

For something like this, they're better suited to resolving/giving advice.
