### ISSUE TITLE
HTTPS Issue With Mono 5.20.1.34

### ISSUE THREAD

**Issue by Pingblue** [linuxserver/docker-radarr#77]
When using Mono 5.20.1.34 the version provided with this image https cannot be used but is possible when upgrading Mono to 6.6.0.161

```
httpcfg -add -port 9898 -cert /config/domain.com.crt -pvk /config/domain.com.pvk

error loading certificate or private key [Operation is not supported on this platform.]
Usage is:
        httpcfg -add -port NN [-cert CERT -pvk PVK] [-p12 P12 -pwd PASSWORD]
        httpcfg -del -port NN
        httpcfg -list

```

**Comment by aptalca** [comment]
We need a lot more info than just a random little snippet

Need to fill out the issue template

**Comment by Powback** [comment]
@aptalca As of Janauary 2020 TLS 1.0 & TLS 1.1 have reached end of life. 
Certain indexers only allow access through TLS 1.2 now, and mono should be updated in order to support those indexers.

**Comment by thelamer** [comment]
We can try out some `6.6.0` builds of mono and maybe shift LTS to it, but honestly it is a musical chairs of issues. Every mono revision fixes something and breaks something else. It is why we still maintain a 5.14 flag. 
I think the general hope was that NetCore stuff was going to make it's way into stable releases(it is in preview) before we had to worry about another major Mono version bump. 

Can you do me a favor and toss an ephemeral key/cert combo in pastebin that works with httpcfg in mono 6.6.x and not in 5.20.x or the method used to generate?

**Comment by Powback** [comment]
I'm afraid I don't have the details. I just updated to mono 6.6.0 by entering the container and upgraded from mono-project.com. This resolved the 500 response code I was receiving while contacting my indexer. For reference, the indexer I was having issues with was nzbgeek.info

**Comment by mattystorey** [comment]
TLS requests are failing across the board on Linuxserver docker containers - Radarr, Sonarr, and Hydrav2 (for me) all running latest builds. All API calls fail.
