### ISSUE TITLE
Add LFTP to RADARR

### ISSUE THREAD

**Issue by joltman80** [linuxserver/docker-radarr#81]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Please add LFTP to the RADARR container image.  This will allow me to pull files down from my seedbox.

------------------------------

## Expected Behavior
That LFTP is installed by default

## Current Behavior
Currently, LFTP is not installed.

## Steps to Reproduce
1.  Pull and run the LINUXSERVER RADARR Container
2.  Enter the container with EXEC and /bin/bash
3.  run the command "lftp"
4.  Not installed, so I manually install it.

## Environment
Ubuntu 18.04  
**CPU architecture:** x86_64    
**How docker service was installed:**      DOCKER-COMPOSE
This is needed to quickly pull files from my seedbox.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-sonarr/issues/143#issuecomment-586813486
