### ISSUE TITLE
Branch develop is for a previous version of Radarr, set branch to 'Aphrodite' for further updates

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-radarr#89]
New warning/notification on Radarr Preview branch:

"Branch develop is for a previous version of Radarr, set branch to 'Aphrodite' for further updates"

This is probably already known, but just making sure!

Close if already being dealt with. 

Thanks!

**Comment by mason1171** [comment]
Using the preview build. I am also seeing this message

**Comment by mason1171** [comment]
https://www.reddit.com/r/radarr/comments/fr5lkp/radarr_v3_branch_question/
Solution

**Comment by modem7** [comment]
I've changed the branch to aphrodite within my settings, but obviously this doesn't change the image itself

**Comment by nemchik** [comment]
Should be fixed in https://github.com/linuxserver/docker-radarr/pull/90
