### ISSUE TITLE
issue when doing manual searches

### ISSUE THREAD

**Issue by ahiguero** [linuxserver/docker-radarr#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

please see description in the main Radarr repository https://github.com/Radarr/Radarr/issues/4435
------------------------------

## Expected Behavior

I expect manual searches to work
## Current Behavior

they are not working
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by moberg89** [comment]
This seems to be the problem: https://github.com/Radarr/Radarr/issues/342

Workaround:
1. Hop into the container: docker exec -it radarr /bin/bash
2. Do following:
apt install gnupg ca-certificates
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
apt update
apt install mono-devel
3. Restart radarr.
4. Bob is your uncle.

**Comment by j0nnymoe** [comment]
Looks like it was an upstream issue?
